# Generated by Django 3.1.1 on 2021-07-15 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project', '0006_auto_20210715_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recontact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.CharField(max_length=10)),
                ('new_id', models.CharField(max_length=10)),
                ('url', models.URLField(default='', null=True)),
                ('project_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recontact_project_group', to='Project.projectgroup')),
            ],
        ),
    ]
