# Generated by Django 3.1.1 on 2021-08-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recontact_Section', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recontact',
            name='new_id',
        ),
        migrations.RemoveField(
            model_name='recontact',
            name='old_id',
        ),
        migrations.AddField(
            model_name='recontact',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recontact',
            name='pid',
            field=models.CharField(default='testpid', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recontact',
            name='rid',
            field=models.CharField(default='testrid', max_length=50),
            preserve_default=False,
        ),
    ]
