# Generated by Django 4.0.6 on 2022-08-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recontact_Section', '0003_auto_20210831_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recontact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
