# Generated by Django 5.0.6 on 2025-01-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recontact_Section', '0004_alter_recontact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recontact',
            name='url',
            field=models.URLField(default='', max_length=500, null=True),
        ),
    ]
