# Generated by Django 5.0.6 on 2024-07-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClientSupplierAPIIntegration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='celeryCall',
        ),
    ]
