# Generated by Django 4.0.6 on 2023-06-02 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TolunaClientAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurveyEntryRouterQuestions',
        ),
    ]
