# Generated by Django 4.0.6 on 2023-06-02 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0006_customerorganization_threat_potential_score'),
        ('employee', '0004_alter_country_id_alter_employeeprofile_id'),
        ('Project', '0039_alter_project_project_revenue_month'),
        ('TolunaClientAPI', '0002_delete_surveyentryrouterquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDBCountryLanguageMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_country_lang_id', models.CharField(max_length=100)),
                ('client_language_code', models.CharField(blank=True, max_length=100, null=True)),
                ('client_language_name', models.CharField(max_length=100, null=True)),
                ('client_language_description', models.CharField(max_length=100, null=True)),
                ('country_lang_guid', models.CharField(blank=True, max_length=500, null=True)),
                ('country_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.country')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customerorganization')),
                ('lanugage_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.language')),
            ],
        ),
        migrations.AddConstraint(
            model_name='clientdbcountrylanguagemapping',
            constraint=models.UniqueConstraint(fields=('customer', 'lanugage_id', 'country_id'), name='unique_customer_lanugage_id_country_id'),
        ),
    ]
