# Generated by Django 4.0.6 on 2023-06-02 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_customerorganization_threat_potential_score'),
        ('TolunaClientAPI', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientStudyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_type_id', models.IntegerField()),
                ('study_type_name', models.CharField(max_length=100)),
                ('study_type_description', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customerorganization')),
            ],
            options={
                'ordering': ('-modified_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='clientstudytype',
            constraint=models.UniqueConstraint(fields=('customer', 'study_type_id'), name='unique_customer_study_type_id'),
        ),
    ]
