# Generated by Django 4.0.6 on 2023-06-02 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_customerorganization_threat_potential_score'),
        ('TolunaClientAPI', '0004_clientstudytype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientQuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.CharField(max_length=100, null=True)),
                ('category_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customerorganization')),
            ],
            options={
                'ordering': ('-modified_at',),
            },
        ),
        migrations.CreateModel(
            name='ClientDBQuestionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_routable', models.BooleanField(default=False)),
                ('client_question_text', models.CharField(max_length=1000)),
                ('client_question_id', models.CharField(max_length=100, null=True)),
                ('client_answer_type', models.CharField(max_length=300, null=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TolunaClientAPI.clientdbcountrylanguagemapping')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customerorganization')),
                ('ques_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TolunaClientAPI.clientquestioncategory')),
            ],
        ),
        migrations.AddConstraint(
            model_name='clientquestioncategory',
            constraint=models.UniqueConstraint(fields=('customer', 'category_id'), name='unique_customer_category_id'),
        ),
        migrations.AddConstraint(
            model_name='clientdbquestionmapping',
            constraint=models.UniqueConstraint(fields=('customer', 'culture', 'client_question_id'), name='unique_customer_culture_client_question'),
        ),
    ]
