# Generated by Django 4.0.6 on 2023-06-02 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TolunaClientAPI', '0005_clientquestioncategory_clientdbquestionmapping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDBAnswerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_answer_text', models.CharField(max_length=1000, null=True)),
                ('client_answer_internal_name', models.CharField(max_length=1000, null=True)),
                ('client_answer_id', models.IntegerField()),
                ('client_precode', models.CharField(max_length=50, null=True)),
                ('client_question_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TolunaClientAPI.clientdbquestionmapping')),
            ],
        ),
        migrations.AddConstraint(
            model_name='clientdbanswermapping',
            constraint=models.UniqueConstraint(fields=('client_question_mapping', 'client_answer_id'), name='unique_client_question_mapping_client_answer_id'),
        ),
    ]
