# Generated by Django 4.0.6 on 2023-06-02 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0039_alter_project_project_revenue_month'),
        ('Supplier', '0019_suppliercontact_supplier_mail_sent'),
        ('Customer', '0006_customerorganization_threat_potential_score'),
        ('TolunaClientAPI', '0006_clientdbanswermapping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientSubQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subquota_id', models.IntegerField(unique=True)),
                ('current_completes', models.IntegerField(default=0)),
                ('target_completes', models.IntegerField(default=0)),
                ('client_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TolunaClientAPI.clientlayer')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGroupSupplierAdditionalFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_routerurl', models.URLField(blank=True, null=True)),
                ('cscode', models.CharField(max_length=200, unique=True)),
                ('prj_grp_supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Project.projectgroupsupplier')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGroupAdditionalFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_guid', models.CharField(max_length=600, null=True)),
                ('wave_id', models.IntegerField(null=True)),
                ('completion_date', models.DateTimeField(null=True)),
                ('device_types', models.CharField(blank=True, max_length=100)),
                ('survey_recontact', models.BooleanField(default=False)),
                ('completes_remaining', models.IntegerField(default=0)),
                ('country_id', models.IntegerField(default=0)),
                ('collects_pii', models.BooleanField(default=False)),
                ('conversion', models.IntegerField(default=0)),
                ('default_entry_link', models.URLField(max_length=1000, null=True)),
                ('success_entry_link', models.URLField(max_length=1000, null=True)),
                ('failure_entry_link', models.URLField(max_length=1000, null=True)),
                ('overquota_entry_link', models.URLField(max_length=1000, null=True)),
                ('qualityterminate_entry_link', models.URLField(max_length=1000, null=True)),
                ('live_entry_link', models.URLField(max_length=1000, null=True)),
                ('test_entry_link', models.URLField(max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.currency')),
                ('project_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey_additional_field', to='Project.projectgroup')),
                ('study_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TolunaClientAPI.clientstudytype')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDefaultSupplySources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_max_cpi', models.FloatField()),
                ('default_max_completes', models.IntegerField()),
                ('default_max_clicks', models.IntegerField()),
                ('customerOrg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customerorganization')),
                ('supplierOrg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.supplierorganisation')),
            ],
        ),
        migrations.CreateModel(
            name='ClientSurveyPrescreenerQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_end_ans_options', models.TextField(null=True)),
                ('allowedRangeMin', models.IntegerField(null=True)),
                ('allowedRangeMax', models.IntegerField(null=True)),
                ('date_answer_option', models.DateField(null=True)),
                ('is_routable', models.BooleanField(default=False)),
                ('client_name', models.CharField(max_length=50)),
                ('client_answer_mappings', models.ManyToManyField(blank=True, editable=False, to='TolunaClientAPI.clientdbanswermapping')),
                ('client_question_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TolunaClientAPI.clientdbquestionmapping')),
                ('client_subquota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TolunaClientAPI.clientsubquota')),
            ],
        ),
        migrations.CreateModel(
            name='ClientQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_id', models.IntegerField(unique=True)),
                ('completes_required', models.IntegerField(default=0)),
                ('completes_remaining', models.IntegerField(default=0)),
                ('client_survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TolunaClientAPI.projectgroupadditionalfields')),
            ],
        ),
        migrations.AddField(
            model_name='clientlayer',
            name='client_quota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TolunaClientAPI.clientquota'),
        ),
    ]
