# Generated by Django 4.0.6 on 2023-06-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TolunaClientAPI', '0007_clientlayer_clientsubquota_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clientsurveyprescreenerquestions',
            constraint=models.UniqueConstraint(fields=('client_subquota', 'client_question_mapping'), name='unique_subquota_question_mapping_new'),
        ),
    ]
