# Generated by Django 4.0.6 on 2023-06-02 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TolunaClientAPI', '0008_clientsurveyprescreenerquestions_unique_subquota_question_mapping_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyEntryTop7Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='customerdefaultsupplysources',
            constraint=models.UniqueConstraint(fields=('customerOrg', 'supplierOrg'), name='unique_customer_supplier_new'),
        ),
        migrations.AddField(
            model_name='surveyentrytop7questions',
            name='client_questions_mapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TolunaClientAPI.clientdbquestionmapping'),
        ),
    ]
