# Generated by Django 4.0.6 on 2023-08-16 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0008_parentquestion_is_routable_and_more'),
        ('TolunaClientAPI', '0010_remove_clientsurveyprescreenerquestions_unique_subquota_question_mapping_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsurveyprescreenerquestions',
            name='client_answer_mappings1',
        ),
        migrations.RemoveField(
            model_name='clientsurveyprescreenerquestions',
            name='client_question_mapping1',
        ),
        migrations.AddField(
            model_name='clientsurveyprescreenerquestions',
            name='client_answer_mappings',
            field=models.ManyToManyField(blank=True, editable=False, to='Questions.translatedanswer'),
        ),
        migrations.AddField(
            model_name='clientsurveyprescreenerquestions',
            name='client_question_mapping',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Questions.translatedquestion'),
            preserve_default=False,
        ),
    ]
