# Generated by Django 4.0.6 on 2023-08-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TolunaClientAPI', '0011_remove_clientsurveyprescreenerquestions_client_answer_mappings1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientquota',
            name='quota_json_data',
            field=models.JSONField(default=dict, max_length=5000),
        ),
    ]
