# Generated by Django 4.0.6 on 2023-09-13 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TolunaClientAPI', '0012_clientquota_quota_json_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdbcountrylanguagemapping',
            old_name='client_country_lang_id',
            new_name='toluna_client_language_id',
        ),
        migrations.RenameField(
            model_name='clientdbcountrylanguagemapping',
            old_name='client_language_code',
            new_name='zamplia_client_language_id',
        ),
    ]
