# Generated by Django 4.0.6 on 2023-09-29 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TolunaClientAPI', '0013_rename_client_country_lang_id_clientdbcountrylanguagemapping_toluna_client_language_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgroupadditionalfields',
            name='study_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TolunaClientAPI.clientstudytype'),
        ),
    ]
