# Generated by Django 4.0.6 on 2023-10-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TolunaClientAPI', '0014_alter_projectgroupadditionalfields_study_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgroupsupplieradditionalfields',
            name='cscode',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
