# Generated by Django 4.2.10 on 2024-02-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TolunaClientAPI', '0015_alter_projectgroupsupplieradditionalfields_cscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdefaultsupplysources',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
