# Generated by Django 4.0.6 on 2024-03-21 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_customerorganization_threat_potential_score'),
        ('Supplier', '0022_subsupplierorganisation_sub_supplier_quality_type_and_more'),
        ('TolunaClientAPI', '0016_customerdefaultsupplysources_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDefaultSubSupplierSources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_max_cpi', models.FloatField()),
                ('default_max_completes', models.IntegerField()),
                ('default_max_clicks', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('customerOrg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customerorganization')),
                ('sub_supplierOrg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.subsupplierorganisation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='customerdefaultsubsuppliersources',
            constraint=models.UniqueConstraint(fields=('customerOrg', 'sub_supplierOrg'), name='unique_customer_sub_supplier_new'),
        ),
    ]
