# Generated by Django 4.0.6 on 2024-06-11 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_customerorganization_threat_potential_score'),
        ('TolunaClientAPI', '0017_customerdefaultsubsuppliersources_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQualifyParametersCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_incidence_lte', models.FloatField(default=0)),
                ('bid_incidence_gte', models.FloatField(default=0)),
                ('cpi_lte', models.FloatField(default=0)),
                ('cpi_gte', models.FloatField(default=0)),
                ('bid_loi_gte', models.IntegerField(default=0)),
                ('bid_loi_lte', models.IntegerField(default=0)),
                ('conversion_gte', models.IntegerField(default=0)),
                ('client_country_languages', models.ManyToManyField(to='TolunaClientAPI.clientdbcountrylanguagemapping')),
                ('customerOrg', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.customerorganization')),
            ],
        ),
    ]
