# Generated by Django 4.0.6 on 2024-09-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TolunaClientAPI', '0020_remove_clientdbquestionmapping_culture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdbcountrylanguagemapping',
            name='sago_client_language_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
