# Generated by Django 3.1.1 on 2021-02-10 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_answer_text', models.CharField(max_length=255)),
                ('parent_answer_id', models.CharField(default='', max_length=35)),
                ('sequence', models.IntegerField(default=1)),
                ('numeric_min_range', models.IntegerField(default=0, null=True)),
                ('numeric_max_range', models.IntegerField(default=99999, null=True)),
                ('parent_answer_status', models.BooleanField(default=True)),
                ('exclusive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ParentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_question_number', models.CharField(default='', max_length=30)),
                ('parent_question_text', models.CharField(max_length=500)),
                ('parent_question_type', models.CharField(choices=[('SS', 'Single Select'), ('MS', 'Multi Select'), ('NU', 'Numeric'), ('OE', 'Open End'), ('IN', 'Info')], default='SS', max_length=2)),
                ('parent_question_prescreener_type', models.CharField(choices=[('Custom', 'Custom'), ('Standard', 'Standard')], default='Custom', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TranslatedQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_question_text', models.CharField(default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transquestion_created_by', to=settings.AUTH_USER_MODEL)),
                ('lang_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.language')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transquestion_modified_by', to=settings.AUTH_USER_MODEL)),
                ('parent_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.parentquestion')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TranslatedAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_answer', models.CharField(max_length=255)),
                ('translated_answer_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transanswer_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transanswer_modified_by', to=settings.AUTH_USER_MODEL)),
                ('parent_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.parentanswer')),
                ('translated_parent_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.translatedquestion')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='QuestionLogTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_url', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questioncat_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questioncat_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='parentquestion',
            name='parent_question_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.questioncategory'),
        ),
        migrations.AddField(
            model_name='parentanswer',
            name='parent_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.parentquestion'),
        ),
    ]
