# Generated by Django 3.1.1 on 2021-07-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentanswer',
            name='numeric_max_range',
            field=models.IntegerField(blank=True, default=99999, null=True),
        ),
        migrations.AlterField(
            model_name='parentanswer',
            name='numeric_min_range',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='parentanswer',
            name='parent_answer_id',
            field=models.CharField(default='', max_length=85),
        ),
        migrations.AlterField(
            model_name='parentquestion',
            name='parent_question_number',
            field=models.CharField(default='', max_length=80),
        ),
    ]
