# Generated by Django 3.1.1 on 2021-10-26 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_auto_20210715_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentquestion',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='translatedquestion',
            options={'ordering': ('-id',)},
        ),
    ]
