# Generated by Django 3.1.1 on 2022-06-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_auto_20211026_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentquestion',
            name='parent_question_prescreener_type',
            field=models.CharField(choices=[('Custom', 'Custom'), ('Standard', 'Standard'), ('API', 'API')], default='Custom', max_length=10),
        ),
    ]
