# Generated by Django 4.0.6 on 2023-08-16 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TolunaClientAPI', '0009_surveyentrytop7questions_and_more'),
        ('Questions', '0007_alter_parentanswer_id_alter_parentquestion_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentquestion',
            name='is_routable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='category_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='translatedquestion',
            name='apidbcountrylangmapping',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TolunaClientAPI.clientdbcountrylanguagemapping'),
        ),
        migrations.AlterField(
            model_name='parentanswer',
            name='parent_answer_text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='parentquestion',
            name='parent_question_prescreener_type',
            field=models.CharField(choices=[('Custom', 'Custom'), ('Standard', 'Standard'), ('API', 'API'), ('TolunaAPI', 'TolunaAPI')], default='Custom', max_length=10),
        ),
        migrations.AlterField(
            model_name='parentquestion',
            name='parent_question_type',
            field=models.CharField(choices=[('SS', 'Single Select'), ('MS', 'Multi Select'), ('NU', 'Numeric'), ('OE', 'Open End'), ('IN', 'Info'), ('DT', 'Date'), ('CT', 'ComputedType')], default='SS', max_length=50),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='translatedanswer',
            name='translated_answer',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='translatedquestion',
            name='translated_question_text',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
