# Generated by Django 4.2.10 on 2024-02-07 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0050_zipcode_question_id_and_more'),
        ('Questions', '0008_parentquestion_is_routable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentanswer',
            name='answer_internal_name',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='parentanswer',
            name='disqo_answer_id',
            field=models.CharField(default='', max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='parentanswer',
            name='disqo_question_id',
            field=models.CharField(default='', max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='parentanswer',
            name='disqo_question_key',
            field=models.CharField(default='', max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='parentanswer',
            name='internal_question_id',
            field=models.CharField(default='', max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='parentanswer',
            name='toluna_answer_id',
            field=models.CharField(default='', max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='parentanswer',
            name='toluna_question_id',
            field=models.CharField(default='', max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='parentanswer',
            name='zamplia_answer_id',
            field=models.CharField(default='', max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='parentanswer',
            name='zamplia_question_id',
            field=models.CharField(default='', max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='parentquestion',
            name='disqo_question_id',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='parentquestion',
            name='disqo_question_key',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='parentquestion',
            name='internal_parent_question_text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='parentquestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parentquestion',
            name='toluna_is_routable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parentquestion',
            name='toluna_question_category_id',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='parentquestion',
            name='toluna_question_id',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='parentquestion',
            name='zamplia_is_routable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parentquestion',
            name='zamplia_question_id',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='translatedanswer',
            name='answer_internal_name',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='translatedanswer',
            name='disqo_answer_id',
            field=models.CharField(default='', max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='translatedanswer',
            name='disqo_question_id',
            field=models.CharField(default='', max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='translatedanswer',
            name='disqo_question_key',
            field=models.CharField(default='', max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='translatedanswer',
            name='internal_answer_id',
            field=models.CharField(default='', max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='translatedanswer',
            name='internal_question_id',
            field=models.CharField(default='', max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='translatedanswer',
            name='toluna_answer_id',
            field=models.CharField(default='', max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='translatedanswer',
            name='toluna_question_id',
            field=models.CharField(default='', max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='translatedanswer',
            name='zamplia_answer_id',
            field=models.CharField(default='', max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='translatedanswer',
            name='zamplia_question_id',
            field=models.CharField(default='', max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='translatedquestion',
            name='Internal_question_id',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='translatedquestion',
            name='disqo_question_id',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='translatedquestion',
            name='disqo_question_key',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='translatedquestion',
            name='internal_question_text',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='translatedquestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='translatedquestion',
            name='parent_question_category',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Questions.questioncategory'),
        ),
        migrations.AddField(
            model_name='translatedquestion',
            name='parent_question_prescreener_type',
            field=models.CharField(choices=[('Custom', 'Custom'), ('Standard', 'Standard')], default='Custom', max_length=10),
        ),
        migrations.AddField(
            model_name='translatedquestion',
            name='parent_question_type',
            field=models.CharField(choices=[('SS', 'Single Select'), ('MS', 'Multi Select'), ('NU', 'Numeric'), ('OE', 'Open End'), ('IN', 'Info'), ('DT', 'Date'), ('CT', 'ComputedType'), ('CTZIP', 'ComputedTypezip'), ('ZIP', 'zip')], default='SS', max_length=50),
        ),
        migrations.AddField(
            model_name='translatedquestion',
            name='toluna_is_routable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='translatedquestion',
            name='toluna_question_category_id',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='translatedquestion',
            name='toluna_question_id',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='translatedquestion',
            name='zamplia_is_routable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='translatedquestion',
            name='zamplia_question_id',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='parentanswer',
            name='parent_answer_text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='parentanswer',
            name='parent_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Questions.parentquestion'),
        ),
        migrations.AlterField(
            model_name='parentquestion',
            name='parent_question_category',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Questions.questioncategory'),
        ),
        migrations.AlterField(
            model_name='parentquestion',
            name='parent_question_text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='parentquestion',
            name='parent_question_type',
            field=models.CharField(choices=[('SS', 'Single Select'), ('MS', 'Multi Select'), ('NU', 'Numeric'), ('OE', 'Open End'), ('IN', 'Info'), ('DT', 'Date'), ('CT', 'ComputedType'), ('CTZIP', 'ComputedTypezip'), ('ZIP', 'zip')], default='SS', max_length=50),
        ),
        migrations.AlterField(
            model_name='translatedanswer',
            name='parent_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Questions.parentanswer'),
        ),
        migrations.AlterField(
            model_name='translatedanswer',
            name='translated_answer',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='translatedanswer',
            name='translated_parent_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Questions.translatedquestion'),
        ),
        migrations.AlterField(
            model_name='translatedquestion',
            name='lang_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.language'),
        ),
        migrations.AlterField(
            model_name='translatedquestion',
            name='parent_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Questions.parentquestion'),
        ),
        migrations.AlterField(
            model_name='translatedquestion',
            name='translated_question_text',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='ZipCodeMappingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=255)),
                ('parent_answer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Questions.translatedanswer')),
            ],
        ),
    ]
