# Generated by Django 4.0.6 on 2024-03-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0009_parentanswer_answer_internal_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentanswer',
            name='lucid_answer_id',
            field=models.CharField(default='', max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='parentanswer',
            name='lucid_question_id',
            field=models.CharField(default='', max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='parentquestion',
            name='lucid_question_id',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='translatedanswer',
            name='lucid_answer_id',
            field=models.CharField(default='', max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='translatedanswer',
            name='lucid_question_id',
            field=models.CharField(default='', max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='translatedquestion',
            name='lucid_question_id',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
    ]
