# Generated by Django 5.0.6 on 2024-07-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0010_parentanswer_lucid_answer_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionLogTable',
        ),
    ]
