# Generated by Django 5.0.8 on 2024-08-20 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0011_delete_questionlogtable'),
        ('TolunaClientAPI', '0020_remove_clientdbquestionmapping_culture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentquestion',
            name='apidbcountrylangmapping',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TolunaClientAPI.clientdbcountrylanguagemapping'),
        ),
    ]
