# Generated by Django 4.0.6 on 2024-09-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0012_parentquestion_apidbcountrylangmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentanswer',
            name='sago_answer_id',
            field=models.CharField(default='', max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='parentanswer',
            name='sago_question_id',
            field=models.CharField(default='', max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='parentquestion',
            name='sago_question_id',
            field=models.CharField(default='', max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='translatedanswer',
            name='sago_answer_id',
            field=models.CharField(default='', max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='translatedanswer',
            name='sago_question_id',
            field=models.CharField(default='', max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='translatedquestion',
            name='sago_question_id',
            field=models.CharField(default='', max_length=85, null=True),
        ),
    ]
