# Generated by Django 4.0.6 on 2024-10-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0013_parentanswer_sago_answer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentquestion',
            name='parent_question_type',
            field=models.CharField(choices=[('SS', 'Single Select'), ('MS', 'Multi Select'), ('NU', 'Numeric'), ('OE', 'Open End'), ('IN', 'Info'), ('DT', 'Date'), ('CT', 'ComputedType'), ('CTZIP', 'ComputedTypezip'), ('ZIP', 'zip'), ('FU', 'File Upload')], default='SS', max_length=50),
        ),
        migrations.AlterField(
            model_name='translatedquestion',
            name='parent_question_type',
            field=models.CharField(choices=[('SS', 'Single Select'), ('MS', 'Multi Select'), ('NU', 'Numeric'), ('OE', 'Open End'), ('IN', 'Info'), ('DT', 'Date'), ('CT', 'ComputedType'), ('CTZIP', 'ComputedTypezip'), ('ZIP', 'zip'), ('FU', 'File Upload')], default='SS', max_length=50),
        ),
    ]
