# Generated by Django 3.1.1 on 2021-02-10 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '__first__'),
        ('Questions', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGroupPrescreener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowedRangeMin', models.CharField(default='0', max_length=100)),
                ('allowedRangeMax', models.CharField(default='100', max_length=100)),
                ('sequence', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowedoptions', models.ManyToManyField(blank=True, to='Questions.TranslatedAnswer')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescreener_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescreener_modified_by', to=settings.AUTH_USER_MODEL)),
                ('project_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.projectgroup')),
                ('translated_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.translatedquestion')),
            ],
            options={
                'ordering': ('sequence',),
            },
        ),
        migrations.CreateModel(
            name='LogTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
