# Generated by Django 3.1.1 on 2022-01-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prescreener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtable',
            name='table_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='logtable',
            name='table_primary_key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
