# Generated by Django 3.1.1 on 2022-02-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prescreener', '0002_auto_20220122_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtable',
            name='post_save_data',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='logtable',
            name='pre_save_data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
