# Generated by Django 3.1.1 on 2022-03-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prescreener', '0003_auto_20220211_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtable',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='table_name',
            field=models.TextField(null=True),
        ),
    ]
