# Generated by Django 3.1.1 on 2022-04-25 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0025_auto_20220425_2256'),
        ('Prescreener', '0004_auto_20220301_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGroupSupplierPrescreenerEnabled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prj_grp_prescreener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prj_grp_supp_prscrner_enable', to='Prescreener.projectgroupprescreener')),
                ('prj_grp_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prj_grp_supp_prscrner_enable', to='Project.projectgroupsupplier')),
            ],
        ),
    ]
