# Generated by Django 4.0.6 on 2023-08-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prescreener', '0006_alter_logtable_id_alter_projectgroupprescreener_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroupprescreener',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
    ]
