# Generated by Django 4.2.10 on 2024-02-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prescreener', '0007_projectgroupprescreener_is_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroupprescreener',
            name='allowed_zipcode_list',
            field=models.JSONField(default=list, max_length=1000000),
        ),
    ]
