# Generated by Django 5.0.6 on 2024-07-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prescreener', '0008_projectgroupprescreener_allowed_zipcode_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogTable',
        ),
    ]
