# Generated by Django 3.1.1 on 2021-02-10 17:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=60, unique=True)),
                ('currency_iso', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified_at',),
            },
        ),
        migrations.CreateModel(
            name='CustomerOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_org_name', models.CharField(max_length=150, unique=True)),
                ('customer_organization_type', models.CharField(choices=[('1', 'Wholesaler'), ('2', 'Retailer')], default='1', max_length=1)),
                ('cust_org_address_1', models.CharField(max_length=120)),
                ('cust_org_address_2', models.CharField(blank=True, max_length=120, null=True)),
                ('cust_org_city', models.CharField(max_length=30)),
                ('cust_org_state', models.CharField(max_length=30)),
                ('cust_org_zip', models.CharField(max_length=10)),
                ('cust_org_TAXVATNumber', models.CharField(blank=True, max_length=25, null=True)),
                ('cust_org_website', models.CharField(max_length=100)),
                ('cust_org_other', models.CharField(blank=True, max_length=100, null=True)),
                ('cust_org_ship_to_address_1', models.CharField(max_length=120)),
                ('cust_org_ship_to_address_2', models.CharField(max_length=120, null=True)),
                ('cust_org_ship_to_city', models.CharField(max_length=30)),
                ('cust_org_ship_to_state', models.CharField(max_length=30)),
                ('cust_org_ship_to_zip', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cust_org_created_by', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.currency')),
                ('cust_org_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.country')),
                ('cust_org_ship_to_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ship_to_country', to='employee.country')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cust_org_modified_by', to=settings.AUTH_USER_MODEL)),
                ('sales_person_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified_at',),
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_firstname', models.CharField(max_length=30)),
                ('client_lastname', models.CharField(max_length=30)),
                ('client_email', models.EmailField(max_length=80)),
                ('client_contactnumber', models.CharField(max_length=14, null=True, validators=[django.core.validators.RegexValidator(message="Contact number must be in the format of '+123456789'. Up to 13 digits allowed.", regex='^\\+?1?\\d{9,13}$')])),
                ('client_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_cont_created_by', to=settings.AUTH_USER_MODEL)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customerorganization')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_cont_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified_at',),
            },
        ),
    ]
