# Generated by Django 3.1.1 on 2022-06-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorganization',
            name='cust_org_name',
            field=models.CharField(max_length=150),
        ),
    ]
