# Generated by Django 4.0.6 on 2022-08-03 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_country_theorem_country_id'),
        ('CompanyBankDetails', '__first__'),
        ('Customer', '0002_auto_20220602_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerorganization',
            options={'ordering': ('cust_org_name',)},
        ),
        migrations.AddField(
            model_name='customerorganization',
            name='company_invoice_bank_detail',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='CompanyBankDetails.companyinvoicebankdetail'),
        ),
        migrations.AddField(
            model_name='customerorganization',
            name='cpi_calculation_method',
            field=models.CharField(blank=True, choices=[('1', 'Including GST'), ('2', 'Excluding GST')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='customerorganization',
            name='customer_invoice_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_inv_currencies', to='Customer.currency'),
        ),
        migrations.AddField(
            model_name='customerorganization',
            name='payment_terms',
            field=models.IntegerField(blank=True, default=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerorganization',
            name='cust_org_address_1',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='customerorganization',
            name='cust_org_city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customerorganization',
            name='cust_org_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='customerorganization',
            name='cust_org_ship_to_address_1',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='customerorganization',
            name='cust_org_ship_to_address_2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='customerorganization',
            name='cust_org_ship_to_city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customerorganization',
            name='cust_org_ship_to_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ship_to_country', to='employee.country'),
        ),
        migrations.AlterField(
            model_name='customerorganization',
            name='cust_org_ship_to_state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customerorganization',
            name='cust_org_ship_to_zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerorganization',
            name='cust_org_state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customerorganization',
            name='cust_org_website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerorganization',
            name='cust_org_zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
