# Generated by Django 4.0.6 on 2023-05-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_currency_client_currency_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorganization',
            name='threat_potential_score',
            field=models.IntegerField(default=60),
        ),
    ]
