# Generated by Django 4.0.6 on 2023-09-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='capturePostbackHits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capturedURL', models.TextField(default='')),
                ('method_name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
