# Generated by Django 4.0.6 on 2023-09-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landingpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='landingpageError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capturedError', models.CharField(default='', max_length=5000)),
                ('hitURL', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
