# Generated by Django 4.0.6 on 2023-12-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landingpage', '0002_landingpageerror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpageerror',
            name='hitURL',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
