# Generated by Django 5.0.6 on 2024-07-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landingpage', '0003_alter_landingpageerror_hiturl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='landingpageError',
        ),
    ]
