# Generated by Django 3.1.1 on 2021-09-04 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project', '0011_auto_20210901_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierIdsMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_ids_sent', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.project')),
            ],
        ),
    ]
