# Generated by Django 3.1.1 on 2022-01-13 22:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier_Final_Ids_Email', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieridsmarks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplieridsmarks',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='supplieridsmarks',
            name='supplier_ids_sent',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
    ]
