# Generated by Django 3.1.1 on 2022-03-23 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Supplier_Final_Ids_Email', '0002_auto_20220113_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierFinalIdsCeleryTaskDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_details', models.TextField(blank=True, default='', null=True)),
                ('task_sub_details', models.TextField(blank=True, default='', null=True)),
                ('task_created_datetime', models.DateTimeField(auto_now_add=True)),
                ('task_completed_datetime', models.DateTimeField(blank=True, null=True)),
                ('task_status', models.CharField(blank=True, choices=[('1', 'PENDING'), ('2', 'STARTED'), ('3', 'SUCCESS'), ('4', 'FAILURE'), ('5', 'RETRY'), ('6', 'REVOKED')], default='1', max_length=10, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
