# Generated by Django 4.0.6 on 2022-08-31 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier_Final_Ids_Email', '0004_alter_supplierfinalidscelerytaskdetail_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieridsmarks',
            name='date_available_by',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 18, 32, 2, 624036)),
            preserve_default=False,
        ),
    ]
