# Generated by Django 4.0.6 on 2022-11-08 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier_Final_Ids_Email', '0005_supplieridsmarks_date_available_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieridsmarks',
            name='approved_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplieridsmarks',
            name='supplier_ids_approved',
            field=models.BooleanField(default=False),
        ),
    ]
