# Generated by Django 4.0.6 on 2022-12-20 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Supplier_Final_Ids_Email', '0006_supplieridsmarks_approved_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplieridsmarks',
            old_name='supplier_ids_approved',
            new_name='final_ids_sent',
        ),
        migrations.RemoveField(
            model_name='supplieridsmarks',
            name='approved_date',
        ),
        migrations.RemoveField(
            model_name='supplieridsmarks',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='supplieridsmarks',
            name='date_available_by',
        ),
        migrations.RemoveField(
            model_name='supplieridsmarks',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='supplieridsmarks',
            name='supplier_ids_sent',
        ),
        migrations.AddField(
            model_name='supplieridsmarks',
            name='final_ids_available_by',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='supplieridsmarks',
            name='final_ids_sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_ids_sent_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplieridsmarks',
            name='final_ids_sent_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='supplieridsmarks',
            name='reconciled_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reconciled_projects', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplieridsmarks',
            name='reconciled_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplieridsmarks',
            name='scrubbed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplieridsmarks',
            name='scrubbed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrubbed_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplieridsmarks',
            name='scrubbed_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='supplieridsmarks',
            name='supplier_ids_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplieridsmarks',
            name='supplier_ids_approval_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='supplieridsmarks',
            name='supplier_ids_approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_ids_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='supplierFinalIdsDeploy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_list', models.JSONField(null=True)),
                ('final_ids_deployed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_ids_deployed_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
