# Generated by Django 4.0.6 on 2023-04-28 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0018_remove_supplierorganisation_total_surveyside_counts_and_more'),
        ('Supplier_Final_Ids_Email', '0007_rename_supplier_ids_approved_supplieridsmarks_final_ids_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierfinalidsdeploy',
            name='project_list_code',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='supplierfinalidsdeploy',
            name='supplier',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Supplier.supplierorganisation'),
        ),
    ]
