# Generated by Django 5.0.6 on 2024-07-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier_Final_Ids_Email', '0008_supplierfinalidsdeploy_project_list_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplierFinalIdsCeleryTaskDetail',
        ),
    ]
