# Generated by Django 3.1.1 on 2022-06-02 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0004_auto_20220602_1600'),
        ('employee', '0003_country_theorem_country_id'),
        ('Project', '0027_auto_20220602_1600'),
        ('affiliaterouter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateRouterQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=1)),
                ('languages', models.ManyToManyField(to='Project.Language')),
                ('parent_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.parentquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50, null=True)),
                ('genareted_visitor_id', models.CharField(max_length=255, null=True)),
                ('user_agent', models.CharField(max_length=255, null=True)),
                ('source', models.CharField(max_length=255, null=True)),
                ('ruid', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorSurveyRedirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_number', models.CharField(max_length=100, null=True)),
                ('supplier_survey_url', models.CharField(max_length=500, null=True)),
                ('supplier_surveys_count', models.CharField(max_length=10, null=True)),
                ('respondent_status', models.CharField(choices=[('3', 'ClientSide Redirect'), ('4', 'Complete'), ('5', 'Terminate'), ('6', 'Quota Full'), ('7', 'Security Terminate')], default='3', max_length=3)),
                ('priority', models.BooleanField(default=False)),
                ('visitor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitor_survey_redirect', to='affiliaterouter.visitors')),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateRouterQuestionsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_end_answer', models.TextField(blank=True, null=True)),
                ('received_answers_id', models.CharField(max_length=255, unique=True)),
                ('affiliate_router_ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_router_question_data', to='affiliaterouter.affiliaterouterquestions')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_router_question_data', to='employee.country')),
                ('parent_answers', models.ManyToManyField(to='Questions.ParentAnswer')),
                ('parent_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_router_question_data', to='Questions.parentquestion')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_router_question_data', to='affiliaterouter.visitors')),
            ],
        ),
        migrations.AddConstraint(
            model_name='affiliaterouterquestionsdata',
            constraint=models.UniqueConstraint(fields=('visitor', 'parent_question'), name='unique_visitor_parent_question'),
        ),
    ]
