# Generated by Django 3.1.1 on 2022-06-27 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliaterouter', '0002_auto_20220602_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorURLParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_extra_params', models.TextField(blank=True, null=True)),
                ('visitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='url_parameter', to='affiliaterouter.visitors')),
            ],
        ),
    ]
