# Generated by Django 3.1.1 on 2022-08-02 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliaterouter', '0003_visitorurlparameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorurlparameters',
            name='pub_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitorurlparameters',
            name='rsid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='VisitorEntryExitLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_url', models.CharField(blank=True, max_length=500, null=True)),
                ('exit_url', models.CharField(blank=True, max_length=500, null=True)),
                ('visitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entry_exit_link', to='affiliaterouter.visitors')),
            ],
        ),
    ]
