# Generated by Django 4.0.6 on 2023-07-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliaterouter', '0006_affiliaterouterquestionsdata_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorurlparameters',
            name='entry_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='visitorurlparameters',
            name='exit_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
