# Generated by Django 4.0.6 on 2023-08-24 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_country_id_alter_employeeprofile_id'),
        ('affiliaterouter', '0007_visitorurlparameters_entry_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliaterouterquestions',
            name='client_pipeline',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='affiliaterouterquestionsdata',
            name='extra_response_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitors',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitors_country_store', to='employee.country'),
        ),
        migrations.AddField(
            model_name='visitors',
            name='rsid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
