# Generated by Django 4.0.6 on 2024-03-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliaterouter', '0008_affiliaterouterquestions_client_pipeline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliaterouterquestionsdata',
            name='open_end_answer',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
