# Generated by Django 4.0.6 on 2024-03-14 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0010_parentanswer_lucid_answer_id_and_more'),
        ('affiliaterouter', '0009_alter_affiliaterouterquestionsdata_open_end_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliaterouterquestions',
            name='parent_question',
        ),
        migrations.RemoveField(
            model_name='affiliaterouterquestionsdata',
            name='affiliate_router_ques',
        ),
        migrations.AddField(
            model_name='affiliaterouterquestions',
            name='translated_question',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='Questions.translatedquestion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affiliaterouterquestionsdata',
            name='parent_answers',
            field=models.ManyToManyField(to='Questions.translatedanswer'),
        ),
        migrations.AlterField(
            model_name='affiliaterouterquestionsdata',
            name='parent_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_router_question_data', to='Questions.translatedquestion'),
        ),
    ]
