# Generated by Django 4.0.6 on 2024-04-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliaterouter', '0010_remove_affiliaterouterquestions_parent_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorsurveyredirect',
            name='supplier_surveys_count',
        ),
        migrations.AddField(
            model_name='visitors',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visitors',
            name='respondent_status',
            field=models.CharField(choices=[('1', 'Visit'), ('2', 'ClientSide Redirect')], default='1', max_length=3),
        ),
        migrations.AlterField(
            model_name='visitorsurveyredirect',
            name='respondent_status',
            field=models.CharField(choices=[('1', 'Visit'), ('2', 'ClientSide Redirect')], default='3', max_length=3),
        ),
        migrations.DeleteModel(
            name='VisitorEntryExitLinks',
        ),
    ]
