# Generated by Django 4.0.6 on 2024-04-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliaterouter', '0011_remove_visitorsurveyredirect_supplier_surveys_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='subsource',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
