# Generated by Django 4.0.6 on 2024-04-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliaterouter', '0013_routerexception_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReRoutingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitorId', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=80)),
            ],
        ),
    ]
