# Generated by Django 4.0.6 on 2024-04-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliaterouter', '0014_reroutinguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='reroutinguser',
            name='usc',
            field=models.CharField(default='internal', max_length=255),
        ),
    ]
