# Generated by Django 4.0.6 on 2024-04-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliaterouter', '0015_reroutinguser_usc'),
    ]

    operations = [
        migrations.AddField(
            model_name='reroutinguser',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
