# Generated by Django 4.0.6 on 2024-05-01 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliaterouter', '0016_reroutinguser_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalVisitorsRouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_url', models.CharField(blank=True, max_length=500, null=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliaterouter.visitors')),
            ],
        ),
    ]
