# Generated by Django 4.0.6 on 2024-05-08 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliaterouter', '0018_totalvisitorsrouts_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalvisitorsrouts',
            name='created_at',
        ),
    ]
