# Generated by Django 4.0.6 on 2024-05-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliaterouter', '0019_remove_totalvisitorsrouts_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalvisitorsrouts',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
