# Generated by Django 5.0.6 on 2024-07-18 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliaterouter', '0020_totalvisitorsrouts_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RouterException',
        ),
    ]
