# Generated by Django 3.1.1 on 2021-10-31 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Supplier', '0006_suppliercontact_supplier_email_notify'),
        ('Project', '0013_auto_20211013_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default='', max_length=50, null=True)),
                ('invoice_recieved', models.BooleanField(default=False)),
                ('invoice_date', models.DateField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.project')),
                ('supplier_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.supplierorganisation')),
            ],
        ),
    ]
