# Generated by Django 3.1.1 on 2022-01-13 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0017_auto_20220113_2213'),
        ('Supplier', '0008_auto_20211206_1941'),
        ('Customer', '0001_initial'),
        ('SupplierInvoice', '0002_auto_20211129_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierinvoice',
            old_name='cpi',
            new_name='conversion_rate',
        ),
        migrations.RemoveField(
            model_name='supplierinvoice',
            name='completes',
        ),
        migrations.RemoveField(
            model_name='supplierinvoice',
            name='invoice_recieved',
        ),
        migrations.RemoveField(
            model_name='supplierinvoice',
            name='project',
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.currency'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='invoice_status',
            field=models.CharField(choices=[('1', 'Received'), ('2', 'Paid'), ('3', 'Cancelled')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='total_invoice_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='supplier_org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Supplier.supplierorganisation'),
        ),
        migrations.CreateModel(
            name='SupplierInvoiceRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_received', models.BooleanField(default=False)),
                ('cpi', models.FloatField(default=0)),
                ('completes', models.IntegerField(blank=True, null=True)),
                ('invoiced_completes', models.IntegerField(blank=True, null=True)),
                ('invoiced_cpi', models.FloatField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.project')),
                ('supplier_invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SupplierInvoice.supplierinvoice')),
                ('supplier_org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Supplier.supplierorganisation')),
            ],
        ),
    ]
