# Generated by Django 3.1.1 on 2022-03-01 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SupplierInvoice', '0003_auto_20220113_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoicePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_deductible', models.FloatField(blank=True, null=True)),
                ('tds_receivable', models.FloatField(blank=True, null=True)),
                ('total_payable_amount', models.FloatField(blank=True, null=True)),
                ('date_invoice_paid', models.DateField(blank=True, null=True)),
                ('supplier_invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SupplierInvoice.supplierinvoice')),
            ],
        ),
    ]
