# Generated by Django 3.1.1 on 2022-03-09 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SupplierInvoice', '0004_supplierinvoicepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierinvoicerow',
            name='supplier_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SupplierInvoice.supplierinvoice'),
        ),
    ]
