# Generated by Django 4.0.6 on 2022-09-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupplierInvoice', '0006_alter_supplierinvoice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='tax_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='taxable_value',
            field=models.FloatField(default=0),
        ),
    ]
