# Generated by Django 4.0.6 on 2023-07-17 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SupplierInvoice', '0007_supplierinvoice_tax_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='total_from_invoice_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='supplierinvoicerow',
            name='supplier_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SupplierInvoice.supplierinvoice'),
        ),
    ]
