# Generated by Django 4.0.6 on 2024-03-14 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyBankDetails', '0003_alter_companyinvoicebankdetail_company_iban_number_and_more'),
        ('SupplierInvoice', '0008_supplierinvoice_total_from_invoice_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CompanyBankDetails.companydetails'),
        ),
    ]
