# Generated by Django 4.0.6 on 2024-05-30 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0058_projectgroup_client_survey_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SupplierInvoice', '0009_supplierinvoice_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInvoicedApproved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.FloatField(blank=True, null=True)),
                ('expense', models.FloatField(blank=True, null=True)),
                ('margin', models.FloatField(blank=True, null=True)),
                ('invoice_approved_date', models.DateField(auto_now_add=True)),
                ('project_invoice_status', models.CharField(choices=[('1', 'Pending'), ('2', 'Partial Approved'), ('3', 'Approved')], max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_invoice_approved_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_invoice_approved_modified_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Project.project')),
                ('supplier_invoice_row', models.ManyToManyField(to='SupplierInvoice.supplierinvoicerow')),
            ],
        ),
    ]
