# Generated by Django 4.0.6 on 2024-06-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupplierInvoice', '0010_projectinvoicedapproved'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoiceLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceid', models.CharField(default='', max_length=50, null=True)),
                ('supplier_code', models.CharField(default='', max_length=50, null=True)),
                ('ip_address', models.CharField(default='', max_length=50, null=True)),
                ('new_invoice_row_values', models.TextField(blank=True, null=True)),
                ('old_invoice_row_values', models.TextField(blank=True, null=True)),
                ('created_values', models.TextField(blank=True, null=True)),
                ('updated_values', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='projectinvoicedapproved',
            name='supplier_invoice_row',
        ),
        migrations.AddField(
            model_name='projectinvoicedapproved',
            name='operationcost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='clarification',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='created_from',
            field=models.CharField(choices=[('1', 'PanelViewPoint'), ('2', 'SupplierDashboard')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='supplier_invoice_file',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='supplierinvoicepayment',
            name='expected_invoice_payment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='invoice_status',
            field=models.CharField(choices=[('1', 'Received'), ('2', 'Paid'), ('3', 'Cancelled'), ('4', 'Approved'), ('5', 'Need to Clarify by PVP'), ('6', 'Clarification Submitted By Supplier')], default='1', max_length=1),
        ),
    ]
