# Generated by Django 4.0.6 on 2024-06-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupplierInvoice', '0011_supplierinvoicelogs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinvoicedapproved',
            name='project_invoice_status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'System Data CPI Mismatch'), ('3', 'System Data Approved'), ('4', 'Supplier Invoice Mismatch'), ('5', 'Approved')], max_length=2, null=True),
        ),
    ]
