# Generated by Django 5.0.6 on 2024-07-02 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0063_alter_project_project_revenue_month'),
        ('SupplierInvoice', '0012_alter_projectinvoicedapproved_project_invoice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSecondaryAuditApproved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_audit_status', models.CharField(choices=[('1', 'Pending'), ('2', 'System Data CPI Mismatch'), ('3', 'System Data Approved'), ('4', 'Supplier Invoice Mismatch'), ('5', 'Approved')], max_length=2, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Project.project')),
            ],
        ),
    ]
