# Generated by Django 4.0.6 on 2024-11-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupplierInvoice', '0014_delete_supplierinvoicelogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceFileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=500, null=True, upload_to='supplier_invoice_pdf')),
            ],
        ),
    ]
