# Generated by Django 3.1.1 on 2021-08-08 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project', '0008_auto_20210808_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_group_supplier_counter', models.IntegerField(default=0)),
                ('project_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.projectgroup')),
                ('project_group_supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.projectgroupsupplier')),
            ],
        ),
    ]
