# Generated by Django 5.0.6 on 2024-07-18 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logapp', '0001_initial'),
        ('affiliaterouter', '0021_delete_routerexception'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyentrylog',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='surveyentrylog',
            name='project_group',
        ),
        migrations.CreateModel(
            name='RouterException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailed_reason', models.CharField(blank=True, max_length=100000, null=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliaterouter.visitors')),
            ],
        ),
    ]
