# Generated by Django 5.0.6 on 2024-07-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logapp', '0002_remove_surveyentrylog_pid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryAPICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APIname', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
