# Generated by Django 4.0.6 on 2024-09-26 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0006_customerorganization_threat_potential_score'),
        ('Supplier', '0024_delete_supplierbuyerapimodel'),
        ('Project', '0067_alter_project_project_revenue_month'),
        ('Prescreener', '0009_delete_logtable'),
        ('Logapp', '0003_celeryapicalllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Customer.customerorganization'),
        ),
        migrations.AddField(
            model_name='projectgroupprescreenerlogs',
            name='projectgroup_pescreener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Prescreener.projectgroupprescreener'),
        ),
        migrations.AddField(
            model_name='projectgroupsupplierlog',
            name='project_group_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.projectgroupsupplier'),
        ),
        migrations.AddField(
            model_name='surveyentrylog',
            name='glsid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SupplierEnableDisableLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_enabled', models.CharField(blank=True, max_length=20, null=True)),
                ('remove_enabled', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Supplier.supplierorganisation')),
            ],
        ),
        migrations.CreateModel(
            name='SubSupplierLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_data', models.TextField(blank=True, null=True)),
                ('updated_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sub_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Supplier.subsupplierorganisation')),
            ],
        ),
        migrations.CreateModel(
            name='SubSupplierEnableDisableLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_enabled', models.CharField(blank=True, max_length=20, null=True)),
                ('remove_enabled', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sub_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Supplier.subsupplierorganisation')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSupplierCPIUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_cpi', models.FloatField(default=0)),
                ('new_cpi', models.FloatField(default=0)),
                ('source', models.CharField(default='0', max_length=6)),
                ('project_number', models.CharField(default='', max_length=20)),
                ('project_group_number', models.CharField(default='', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectReconciliationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGroupPanelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_enabled', models.BooleanField(default=False)),
                ('panel_disabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('projectgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.projectgroup')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGroupADPanelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adpanel_enabled', models.BooleanField(default=False)),
                ('adpanel_disabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('projectgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.projectgroup')),
            ],
        ),
    ]
