# Generated by Django 4.0.6 on 2024-11-12 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employeeprofile_emp_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='source_id',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='user_type',
            field=models.CharField(choices=[('1', 'Internal'), ('2', 'External')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='emp_type',
            field=models.CharField(choices=[('1', 'Project Manager'), ('2', 'Bidding Manager'), ('3', 'Senior Project Manager'), ('4', 'Accountant Executive'), ('5', 'Panel Manager'), ('6', 'Sales Executive'), ('7', 'Leadership'), ('8', 'Affiliate Manager'), ('9', 'Management Team'), ('10', 'Enginex Supplier')], default='7', max_length=2),
        ),
        migrations.CreateModel(
            name='UserTokenVerifyPasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_token', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertoken_passwdreset_qs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
