# Generated by Django 5.0.6 on 2024-11-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employeeprofile_source_id_employeeprofile_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='contact_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
