# Generated by Django 5.0.6 on 2025-01-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_employeeprofile_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='emp_type',
            field=models.CharField(choices=[('1', 'Project Manager'), ('2', 'Bidding Manager'), ('3', 'Senior Project Manager'), ('4', 'Accountant Executive'), ('5', 'Panel Manager'), ('6', 'Sales Executive'), ('7', 'Leadership'), ('8', 'Affiliate Manager'), ('9', 'Management Team'), ('10', 'Enginex Supplier'), ('11', 'Business Analyst'), ('12', 'Tech Team')], default='7', max_length=2),
        ),
    ]
