# Generated by Django 5.0.6 on 2025-03-04 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employeeprofile_emp_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_ammount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_month', models.IntegerField()),
                ('target_year', models.IntegerField()),
                ('conversion', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
