# Generated by Django 3.1.1 on 2021-05-16 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
        ('Project', '0004_auto_20210516_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='APISupplierOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_supplier_code', models.CharField(default='', max_length=255, null=True)),
                ('api_supplier_name', models.CharField(max_length=150)),
                ('revenue_model', models.CharField(choices=[('F', 'Flat'), ('S', 'Sharing')], default='F', max_length=20)),
                ('revenue_flat_price', models.FloatField(default=0, null=True)),
                ('revenue_sharing_price', models.CharField(default='', max_length=20, null=True)),
                ('billing_details', models.TextField(default='', null=True)),
                ('api_supplier_address1', models.CharField(max_length=150, null=True)),
                ('api_supplier_address2', models.CharField(max_length=150, null=True)),
                ('api_supplier_city', models.CharField(max_length=25, null=True)),
                ('api_supplier_state', models.CharField(max_length=25, null=True)),
                ('api_supplier_zip', models.CharField(max_length=10, null=True)),
                ('default_redirect_url', models.URLField(default='', null=True)),
                ('postback_url', models.URLField(default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('api_supplier_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.country')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_supp_org_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_supp_org_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectGroupAPISupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_redirect_url', models.URLField(default='', null=True)),
                ('postback_url', models.URLField(default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('api_supplier_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_supplier_orga', to='SupplierAPI.apisupplierorganisation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_progrpsupp_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_progrpsupp_modified_by', to=settings.AUTH_USER_MODEL)),
                ('project_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_project_group', to='Project.projectgroup')),
            ],
            options={
                'ordering': ('-modified_at',),
            },
        ),
    ]
