# Generated by Django 3.1.1 on 2021-05-27 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupplierAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectgroupapisupplier',
            name='api_supplier_org',
        ),
        migrations.RemoveField(
            model_name='projectgroupapisupplier',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='projectgroupapisupplier',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='projectgroupapisupplier',
            name='project_group',
        ),
        migrations.DeleteModel(
            name='APISupplierOrganisation',
        ),
        migrations.DeleteModel(
            name='ProjectGroupAPISupplier',
        ),
    ]
