# Generated by Django 3.1.1 on 2021-11-29 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Supplier', '0007_auto_20211129_2003'),
        ('Project', '0014_auto_20211129_2003'),
        ('SupplierAPI', '0002_auto_20210527_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheormReachRelationalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theorm_id', models.CharField(max_length=200, unique=True)),
                ('project_grp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.projectgroupsupplier')),
                ('supplier_org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.supplierorganisation')),
            ],
        ),
    ]
