# Generated by Django 3.1.1 on 2021-11-30 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupplierAPI', '0003_theormreachrelationalmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TheormReachRelationalModel',
        ),
    ]
