# Generated by Django 3.1.1 on 2022-03-01 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0003_country_theorem_country_id'),
        ('Project', '0019_auto_20220301_1947'),
        ('SupplierAPI', '0004_delete_theormreachrelationalmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LucidCountryLanguageMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lucid_country_lang_id', models.CharField(max_length=100, unique=True)),
                ('lucid_language_code', models.CharField(max_length=100, unique=True)),
                ('lucid_language_name', models.CharField(max_length=300, unique=True)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.country')),
                ('lanugage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.language')),
            ],
        ),
    ]
