# Generated by Django 3.1.1 on 2022-06-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupplierAPI', '0005_lucidcountrylanguagemapping'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lucidcountrylanguagemapping',
            constraint=models.UniqueConstraint(fields=('lanugage_id', 'country_id'), name='unique_language_country'),
        ),
    ]
