# Generated by Django 3.1.1 on 2022-06-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupplierAPI', '0006_auto_20220602_1600'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lucidcountrylanguagemapping',
            name='unique_language_country',
        ),
    ]
