# Generated by Django 4.0.6 on 2022-08-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupplierAPI', '0008_auto_20220602_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lucidcountrylanguagemapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
