# Generated by Django 3.1.1 on 2021-12-16 18:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project', '0015_auto_20211206_1941'),
        ('Supplier', '0008_auto_20211206_1941'),
        ('employee', '0002_auto_20211026_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidence', models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('loi', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(1)])),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ManyToManyField(to='employee.Country')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.project')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierInviteDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.FloatField(default=0)),
                ('completes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('supplier_contact', models.ManyToManyField(to='Supplier.SupplierContact')),
                ('supplier_invite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SupplierInviteOnProject.supplierinvite')),
                ('supplier_org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Supplier.supplierorganisation')),
            ],
        ),
    ]
