# Generated by Django 3.1.1 on 2021-02-10 17:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespondentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='0', max_length=6)),
                ('url_type', models.CharField(choices=[('Live', 'Live'), ('Test', 'Test')], default='Live', max_length=4)),
                ('project_number', models.CharField(default='', max_length=20)),
                ('project_group_number', models.CharField(default='', max_length=25)),
                ('project_group_cpi', models.FloatField(default=0)),
                ('supplier_cpi', models.FloatField(default='0')),
                ('resp_status', models.CharField(choices=[('1', 'Visit'), ('2', 'Internal Terminate'), ('3', 'Incomplete'), ('4', 'Complete'), ('5', 'Terminate'), ('6', 'Quotafull'), ('7', 'Security Terminate')], default='1', max_length=1)),
                ('final_detailed_reason', models.CharField(default='', max_length=50)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time_day', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('duration', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyEntryWelcomePageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_1_text', models.TextField(blank=True, null=True)),
                ('row_2_text', models.TextField(blank=True, null=True)),
                ('row_3_text', models.TextField(blank=True, null=True)),
                ('row_4_text', models.TextField(blank=True, null=True)),
                ('row_5_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.language')),
            ],
        ),
        migrations.CreateModel(
            name='RespondentURLDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_url', models.CharField(max_length=255)),
                ('url_safe_string', models.CharField(default='', max_length=100)),
                ('user_agent', models.CharField(default='', max_length=255)),
                ('ip_address', models.CharField(default='', max_length=30)),
                ('pid', models.CharField(default='', max_length=100)),
                ('RID', models.CharField(default='', max_length=50)),
                ('project_redirect_type', models.CharField(choices=[('0', 'Static'), ('1', 'Dynamic')], default='1', max_length=1)),
                ('respondent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Surveyentry.respondentdetail')),
            ],
        ),
        migrations.CreateModel(
            name='RespondentSupplierDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_status', models.CharField(choices=[('Cancel', 'Cancel'), ('Booked', 'Booked'), ('Live', 'Live'), ('Paused', 'Paused'), ('Closed', 'Closed'), ('Reconciled', 'Reconciled'), ('Invoiced', 'Invoiced'), ('Archived', 'Archived')], default='Booked', max_length=10)),
                ('supplier_requiredN', models.IntegerField(default=0)),
                ('supplier_required_clicks', models.IntegerField(default=0)),
                ('supplier_complete_url', models.URLField(default='')),
                ('supplier_terminate_url', models.URLField(default='')),
                ('supplier_quotafull_url', models.URLField(default='')),
                ('supplier_securityterminate_url', models.URLField(default='')),
                ('hash_value', models.CharField(default='', max_length=150)),
                ('respondent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Surveyentry.respondentdetail')),
            ],
        ),
        migrations.CreateModel(
            name='RespondentReconcilation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=1)),
                ('previous_status', models.CharField(choices=[('1', 'Visit'), ('2', 'Internal Terminate'), ('3', 'Incomplete'), ('4', 'Complete'), ('5', 'Terminate'), ('6', 'Quotafull'), ('7', 'Security Terminate')], default='3', max_length=1)),
                ('previous_final_detailed_reason', models.CharField(default='', max_length=50)),
                ('verified_at', models.DateTimeField(auto_now=True)),
                ('respondent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Surveyentry.respondentdetail')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespondentProjectDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_group_status', models.CharField(choices=[('Cancel', 'Cancel'), ('Booked', 'Booked'), ('Live', 'Live'), ('Paused', 'Paused'), ('Closed', 'Closed'), ('Reconciled', 'Reconciled'), ('Invoiced', 'Invoiced'), ('Archived', 'Archived')], default='Booked', max_length=10)),
                ('project_group_loi', models.IntegerField(default=0)),
                ('project_group_completes', models.CharField(default='', max_length=10)),
                ('project_group_clicks', models.CharField(default='', max_length=10)),
                ('project_group_redirectID', models.CharField(default='', max_length=20)),
                ('clientURL', models.URLField(default='')),
                ('project_group_security_check', models.BooleanField(default=True)),
                ('project_group_ip_check', models.BooleanField(default=True)),
                ('project_group_pid_check', models.BooleanField(default=True)),
                ('project_group_allowed_svscore', models.IntegerField(default=20)),
                ('project_group_allowed_dupescore', models.IntegerField(default=80)),
                ('project_group_allowed_fraudscore', models.IntegerField(default=50)),
                ('respondent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Surveyentry.respondentdetail')),
            ],
        ),
        migrations.CreateModel(
            name='RespondentDeviceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_system', models.CharField(default='', max_length=255)),
                ('browser', models.CharField(default='', max_length=255)),
                ('mobile', models.BooleanField(default=False)),
                ('tablet', models.BooleanField(default=False)),
                ('desktop', models.BooleanField(default=False)),
                ('touch_capable', models.BooleanField(default=False)),
                ('bot', models.BooleanField(default=False)),
                ('respondent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Surveyentry.respondentdetail')),
            ],
        ),
        migrations.CreateModel(
            name='respondent_survalidate_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dupescore', models.IntegerField(default=0)),
                ('svscore', models.IntegerField(default=0)),
                ('svid', models.IntegerField(default=0)),
                ('country_accept', models.CharField(default='', max_length=255, null=True)),
                ('country_block', models.CharField(default='', max_length=255, null=True)),
                ('d0', models.IntegerField(default=0)),
                ('d1', models.IntegerField(default=0)),
                ('d2', models.IntegerField(default=0)),
                ('d3', models.IntegerField(default=0)),
                ('d4', models.IntegerField(default=0)),
                ('d5', models.IntegerField(default=0)),
                ('d6', models.IntegerField(default=0)),
                ('reason', models.CharField(default='', max_length=255, null=True)),
                ('f1r', models.CharField(default='', max_length=255, null=True)),
                ('fraudscore', models.IntegerField(default=0)),
                ('f1', models.IntegerField(default=0)),
                ('f2', models.IntegerField(default=0)),
                ('f3', models.IntegerField(default=0)),
                ('f4', models.IntegerField(default=0)),
                ('f5', models.IntegerField(default=0)),
                ('f6', models.IntegerField(default=0)),
                ('f7', models.IntegerField(default=0)),
                ('f8', models.IntegerField(default=0)),
                ('f9', models.IntegerField(default=0)),
                ('f10', models.IntegerField(default=0)),
                ('country', models.CharField(default='', max_length=50, null=True)),
                ('is_mobile', models.IntegerField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('respondent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Surveyentry.respondentdetail')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGroupPrescreenerDataStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_response', models.TextField(default='')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Surveyentry.respondentdetail')),
                ('selected_options', models.ManyToManyField(to='Questions.TranslatedAnswer')),
                ('translated_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.translatedquestion')),
            ],
        ),
    ]
