# Generated by Django 3.1.1 on 2021-03-05 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('Surveyentry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GEOIPAPItable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=100)),
                ('latitude', models.CharField(default='', max_length=100)),
                ('longitude', models.CharField(default='', max_length=100)),
                ('RespondentDetail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Surveyentry.respondentdetail')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.country')),
            ],
        ),
    ]
