# Generated by Django 4.0.6 on 2022-11-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondentpagedetails',
            name='url_extra_params',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
