# Generated by Django 3.1.1 on 2021-04-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0002_geoipapitable'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroupprescreenerdatastore',
            name='text_evalution_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectgroupprescreenerdatastore',
            name='text_evalution_result',
            field=models.CharField(default='', max_length=100),
        ),
    ]
