# Generated by Django 3.1.1 on 2021-05-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0003_auto_20210425_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondentreconcilation',
            name='supplier_verified_id',
            field=models.BooleanField(default=True),
        ),
    ]
