# Generated by Django 3.1.1 on 2021-08-08 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_auto_20210808_0913'),
        ('Surveyentry', '0005_auto_20210715_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondentdetailsrelationalfield',
            name='project_group_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.projectgroupsupplier'),
        ),
    ]
