# Generated by Django 3.1.1 on 2021-08-31 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0006_respondentdetailsrelationalfield_project_group_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondentdetail',
            name='resp_status',
            field=models.CharField(choices=[('1', 'Visit'), ('2', 'Internal Terminate'), ('3', 'Incomplete'), ('4', 'Complete'), ('5', 'Terminate'), ('6', 'Quotafull'), ('7', 'Security Terminate'), ('8', 'Complete Rejected')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='respondentreconcilation',
            name='previous_status',
            field=models.CharField(choices=[('1', 'Visit'), ('2', 'Internal Terminate'), ('3', 'Incomplete'), ('4', 'Complete'), ('5', 'Terminate'), ('6', 'Quotafull'), ('7', 'Security Terminate'), ('8', 'Complete Rejected')], default='3', max_length=1),
        ),
        migrations.CreateModel(
            name='RespondentRoutingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_routing', models.BooleanField(default=False)),
                ('previous_project_group_number', models.CharField(default='', max_length=25)),
                ('base_supplier_cpi', models.FloatField(default=0)),
                ('respondent', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Surveyentry.respondentdetail')),
            ],
        ),
    ]
