# Generated by Django 3.1.1 on 2021-09-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0007_auto_20210831_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondentdetail',
            name='resp_status',
            field=models.CharField(choices=[('1', 'Visit'), ('2', 'Internal Terminate'), ('3', 'Incomplete'), ('4', 'Complete'), ('5', 'Terminate'), ('6', 'Quotafull'), ('7', 'Security Terminate'), ('8', 'Complete Rejected by client'), ('9', 'Complete Rejected by PVP')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='respondentreconcilation',
            name='previous_status',
            field=models.CharField(choices=[('1', 'Visit'), ('2', 'Internal Terminate'), ('3', 'Incomplete'), ('4', 'Complete'), ('5', 'Terminate'), ('6', 'Quotafull'), ('7', 'Security Terminate'), ('8', 'Complete Rejected by client'), ('9', 'Complete Rejected by PVP')], default='3', max_length=1),
        ),
    ]
