# Generated by Django 3.1.1 on 2021-09-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0008_auto_20210901_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondenturldetail',
            name='actual_url',
            field=models.TextField(default='', null=True),
        ),
    ]
