# Generated by Django 3.1.1 on 2021-10-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0010_auto_20211013_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondenturldetail',
            name='ruid',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
