# Generated by Django 3.1.1 on 2021-12-13 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0011_respondenturldetail_ruid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondentdetail',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
