# Generated by Django 3.1.1 on 2022-03-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0012_auto_20211213_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputedOnHoldProjectsRespStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, null=True)),
                ('project_status', models.CharField(max_length=100, null=True)),
                ('customer', models.CharField(max_length=100, null=True)),
                ('completes', models.IntegerField(null=True)),
                ('revenue', models.FloatField(null=True)),
                ('expense', models.FloatField(null=True)),
                ('margin', models.FloatField(null=True)),
                ('project_number', models.CharField(max_length=100, null=True)),
                ('last_complete_date', models.CharField(max_length=100, null=True)),
                ('customercode', models.IntegerField(null=True)),
                ('user_id', models.IntegerField(null=True)),
            ],
        ),
    ]
