# Generated by Django 3.1.1 on 2022-04-01 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0013_computedonholdprojectsrespstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespondentResearchDefenderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('entered_text', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('encoded_page_load_time', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('encoded_pasted_text_data', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('encoded_answer_typed_time', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('encoded_answer_submited_time', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('page_load_time', models.PositiveBigIntegerField(default=0)),
                ('pasted_text_data', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('answer_typed_time', models.PositiveBigIntegerField(default=0)),
                ('answer_submited_time', models.PositiveBigIntegerField(default=0)),
                ('s_text_length', models.PositiveSmallIntegerField(default=50)),
                ('sn_ud', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('sy_nr', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Surveyentry.respondentdetail')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchDefenderResponseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_text', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('entered_q_id', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('entered_similarity_text_length', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('entered_sn_ud', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('entered_sy_nr', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('language_detected', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('pasted_response', models.PositiveIntegerField(default=0)),
                ('typed_response_time', models.FloatField(default=0)),
                ('page_view_time', models.FloatField(default=0)),
                ('garbage_words_score', models.FloatField(default=0)),
                ('similarity_text', models.FloatField(default=0)),
                ('garbage_words', models.PositiveIntegerField(default=0)),
                ('language_detected_score', models.FloatField(default=0)),
                ('profanity_check_score', models.FloatField(default=0)),
                ('pasted_response_score', models.FloatField(default=0)),
                ('profanity_check', models.PositiveIntegerField(default=0)),
                ('engagement_score', models.FloatField(default=0)),
                ('composite_score', models.PositiveIntegerField(default=0)),
                ('client_blacklist', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('research_defender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Surveyentry.respondentresearchdefenderdetail')),
            ],
        ),
    ]
