# Generated by Django 3.1.1 on 2022-05-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0014_researchdefenderresponsedetail_respondentresearchdefenderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondentdetail',
            name='last_page_seen',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
