# Generated by Django 3.1.1 on 2022-06-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0016_remove_respondentdetail_last_page_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondenturldetail',
            name='pub_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='respondentdetail',
            name='final_detailed_reason',
            field=models.CharField(default='', max_length=250),
        ),
    ]
