# Generated by Django 3.1.1 on 2022-06-02 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0017_auto_20220602_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondenturldetail',
            name='pub_id',
        ),
    ]
