# Generated by Django 3.1.1 on 2022-06-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0018_remove_respondenturldetail_pub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondenturldetail',
            name='pub_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
