# Generated by Django 3.1.1 on 2022-06-17 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0019_respondenturldetail_pub_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespondentPageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_page_seen', models.CharField(blank=True, max_length=200, null=True)),
                ('respondent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Surveyentry.respondentdetail')),
            ],
        ),
    ]
