# Generated by Django 3.1.1 on 2022-06-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0021_respondentprojectdetail_research_defender_oe_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondentpagedetails',
            name='url_extra_params',
            field=models.TextField(blank=True, null=True),
        ),
    ]
