# Generated by Django 3.1.1 on 2022-08-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0022_respondentpagedetails_url_extra_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondentpagedetails',
            name='clientredirect_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='respondentpagedetails',
            name='endpageurl_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='respondentpagedetails',
            name='entry_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='respondentpagedetails',
            name='postbackurl_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='respondentpagedetails',
            name='suppliersideredirect_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='respondenturldetail',
            name='rsid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
