# Generated by Django 4.0.6 on 2022-08-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0023_auto_20220802_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchdefenderresponsedetail',
            name='entered_q_id',
            field=models.CharField(blank=True, default='', max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='researchdefenderresponsedetail',
            name='entered_similarity_text_length',
            field=models.CharField(blank=True, default='', max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='researchdefenderresponsedetail',
            name='entered_sn_ud',
            field=models.CharField(blank=True, default='', max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='researchdefenderresponsedetail',
            name='entered_sy_nr',
            field=models.CharField(blank=True, default='', max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='researchdefenderresponsedetail',
            name='entered_text',
            field=models.CharField(blank=True, default='', max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='researchdefenderresponsedetail',
            name='language_detected',
            field=models.CharField(blank=True, default='', max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='respondentprojectdetail',
            name='project_group_status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Booked', 'Booked'), ('Live', 'Live'), ('Paused', 'Paused'), ('Closed', 'Closed'), ('Reconciled', 'Reconciled'), ('ReadyForInvoice', 'ReadyForInvoice'), ('ReadyForInvoiceApproved', 'ReadyForInvoiceApproved'), ('Invoiced', 'Invoiced'), ('Archived', 'Archived')], default='Booked', max_length=23),
        ),
        migrations.AlterField(
            model_name='respondentresearchdefenderdetail',
            name='encoded_answer_submited_time',
            field=models.CharField(blank=True, default='', max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='respondentresearchdefenderdetail',
            name='encoded_answer_typed_time',
            field=models.CharField(blank=True, default='', max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='respondentresearchdefenderdetail',
            name='encoded_page_load_time',
            field=models.CharField(blank=True, default='', max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='respondentresearchdefenderdetail',
            name='encoded_pasted_text_data',
            field=models.CharField(blank=True, default='', max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='respondentresearchdefenderdetail',
            name='entered_text',
            field=models.CharField(blank=True, default='', max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='respondentresearchdefenderdetail',
            name='pasted_text_data',
            field=models.CharField(blank=True, default='', max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='respondentresearchdefenderdetail',
            name='sn_ud',
            field=models.CharField(blank=True, default='', max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='respondentresearchdefenderdetail',
            name='sy_nr',
            field=models.CharField(blank=True, default='', max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='respondentsupplierdetail',
            name='supplier_status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Booked', 'Booked'), ('Live', 'Live'), ('Paused', 'Paused'), ('Closed', 'Closed'), ('Reconciled', 'Reconciled'), ('ReadyForInvoice', 'ReadyForInvoice'), ('ReadyForInvoiceApproved', 'ReadyForInvoiceApproved'), ('Invoiced', 'Invoiced'), ('Archived', 'Archived')], default='Booked', max_length=23),
        ),
    ]
