# Generated by Django 4.0.6 on 2022-08-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0024_alter_researchdefenderresponsedetail_entered_q_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondentpagedetails',
            name='last_page_seen',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
