# Generated by Django 4.0.6 on 2022-08-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0026_alter_computedonholdprojectsrespstats_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondenturldetail',
            name='ip_address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
