# Generated by Django 4.0.6 on 2022-11-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0002_alter_respondentpagedetails_url_extra_params'),
        ('Surveyentry', '0027_alter_respondenturldetail_ip_address'),
    ]

    operations = [
    ]
