# Generated by Django 4.0.6 on 2022-11-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0028_merge_20221103_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondentpagedetails',
            name='total_question_shown',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='respondentpagedetails',
            name='url_extra_params',
            field=models.JSONField(default=dict),
        ),
    ]
