# Generated by Django 4.0.6 on 2022-12-20 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0029_respondentpagedetails_total_question_shown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondentpagedetails',
            name='url_extra_params',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.CreateModel(
            name='AffiliateRouterExtraURLParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubid', models.CharField(max_length=500, null=True, unique=True)),
                ('zoneid', models.CharField(max_length=500, null=True, unique=True)),
                ('campaignid', models.CharField(max_length=500, null=True)),
                ('os', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=5, null=True)),
                ('cost', models.FloatField(null=True)),
                ('device', models.CharField(max_length=50, null=True)),
                ('browser', models.CharField(max_length=100, null=True)),
                ('browserversion', models.CharField(max_length=10, null=True)),
                ('osversion', models.CharField(max_length=20, null=True)),
                ('countryname', models.CharField(max_length=100, null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('useragent', models.CharField(max_length=50, null=True)),
                ('language', models.CharField(max_length=100, null=True)),
                ('connection_type', models.CharField(max_length=50, null=True)),
                ('carrier', models.CharField(max_length=100, null=True)),
                ('clickID', models.CharField(max_length=100, null=True, unique=True)),
                ('bannerid', models.CharField(max_length=100, null=True, unique=True)),
                ('user_activity', models.CharField(max_length=100, null=True)),
                ('payout', models.FloatField(null=True)),
                ('zone_type', models.CharField(max_length=50, null=True)),
                ('respondent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Surveyentry.respondentdetail')),
            ],
        ),
    ]
