# Generated by Django 4.0.6 on 2023-04-28 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0030_alter_respondentpagedetails_url_extra_params_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondentdetail',
            name='supplier_cpi',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='RespondentClientSupplyAdditionalParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cscode', models.CharField(max_length=255)),
                ('guid', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('respondent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Surveyentry.respondentdetail')),
            ],
        ),
    ]
