# Generated by Django 4.0.6 on 2023-05-10 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0031_alter_respondentdetail_supplier_cpi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchDefenderSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_number', models.CharField(max_length=100, null=True)),
                ('country_mismatch', models.FloatField(default=0)),
                ('destination', models.CharField(max_length=250, null=True)),
                ('duplicate_potential', models.CharField(max_length=100, null=True)),
                ('failure_reason', models.CharField(choices=[('01', 'Everything all right'), ('02', 'Duplicate entrant into survey'), ('03', 'User Emulator'), ('04', 'Nefarious VPN usage detected'), ('05', 'TOR network detected'), ('06', 'Public proxy server detected'), ('07', 'Web proxy service used'), ('08', 'Web crawler usage detected'), ('09', 'Internet fraudster detected'), ('10', 'Retail and ad-tech fraudster detected '), ('11', 'IP Address subnet detected'), ('12', 'Recent Abuse detected'), ('13', 'Duplicate Survey Group detected'), ('14', 'Navigator Webdriver detected'), ('15', 'Developer tool detected')], default='01', max_length=2)),
                ('duplicate_initial_ud', models.CharField(max_length=250, null=True)),
                ('flag', models.FloatField(default=0)),
                ('duplicate_score', models.FloatField(default=0)),
                ('sn_ud', models.CharField(max_length=250, null=True)),
                ('threat_potential', models.CharField(max_length=100, null=True)),
                ('country_code', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('respondent_risk', models.FloatField(default=0)),
                ('respondent_ud', models.CharField(max_length=250, null=True)),
                ('threat_potential_score', models.FloatField(default=0)),
                ('respondent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Surveyentry.respondentdetail')),
            ],
        ),
    ]
