# Generated by Django 4.0.6 on 2023-07-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0032_researchdefendersearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondentdetail',
            name='resp_status',
            field=models.CharField(choices=[('1', 'Visit'), ('2', 'Internal Terminate'), ('3', 'Incomplete'), ('4', 'Complete'), ('5', 'Terminate'), ('6', 'Quotafull'), ('7', 'Security Terminate'), ('8', 'Complete Rejected by client'), ('9', 'Client Rejected')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='respondentreconcilation',
            name='previous_status',
            field=models.CharField(choices=[('1', 'Visit'), ('2', 'Internal Terminate'), ('3', 'Incomplete'), ('4', 'Complete'), ('5', 'Terminate'), ('6', 'Quotafull'), ('7', 'Security Terminate'), ('8', 'Complete Rejected by client'), ('9', 'Client Rejected')], default='3', max_length=1),
        ),
    ]
