# Generated by Django 4.0.6 on 2023-08-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0033_alter_respondentdetail_resp_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondentdevicedetail',
            name='mac_address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
