# Generated by Django 4.0.6 on 2023-08-12 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0034_respondentdevicedetail_mac_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientBackTrackingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_url_params', models.JSONField(default={}, max_length=1000)),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Surveyentry.respondentdetail')),
            ],
        ),
    ]
