# Generated by Django 4.0.6 on 2023-08-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0035_clientbacktrackingdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbacktrackingdetails',
            name='captured_url_params',
            field=models.JSONField(default=dict, max_length=1000),
        ),
    ]
