# Generated by Django 4.0.6 on 2023-08-16 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prescreener', '0007_projectgroupprescreener_is_enable'),
        ('Surveyentry', '0036_alter_clientbacktrackingdetails_captured_url_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroupprescreenerdatastore',
            name='calculated_response',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectgroupprescreenerdatastore',
            name='prescreener_question',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Prescreener.projectgroupprescreener'),
        ),
    ]
