# Generated by Django 4.0.6 on 2023-08-24 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliaterouter', '0007_visitorurlparameters_entry_url_and_more'),
        ('Surveyentry', '0037_projectgroupprescreenerdatastore_calculated_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffialiateRouterRelationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Surveyentry.respondentdetail')),
                ('visitor_survey_redirect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliaterouter.visitorsurveyredirect')),
            ],
        ),
    ]
