# Generated by Django 4.0.6 on 2023-08-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0038_affialiaterouterrelationfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondentreconcilation',
            name='previous_final_detailed_reason',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
