# Generated by Django 4.0.6 on 2023-08-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0039_alter_respondentreconcilation_previous_final_detailed_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondentdetail',
            name='final_detailed_reason',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
