# Generated by Django 4.0.6 on 2023-09-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0040_alter_respondentdetail_final_detailed_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondentsupplierdetail',
            name='supplier_lucid_min_cpi',
            field=models.FloatField(null=True),
        ),
    ]
