# Generated by Django 4.0.6 on 2023-09-26 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0041_respondentsupplierdetail_supplier_lucid_min_cpi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchDefenderFailureReasonDataStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_reason', models.CharField(default='', max_length=250)),
                ('defender_response', models.JSONField(default=dict, max_length=1000)),
                ('respondent', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Surveyentry.respondentdetail')),
            ],
        ),
    ]
