# Generated by Django 4.0.6 on 2023-10-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0042_researchdefenderfailurereasondatastore'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondentdetail',
            name='client_landing_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
