# Generated by Django 4.0.6 on 2024-04-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0044_respondenturldetail_sub_sup_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondentdetail',
            name='us',
            field=models.CharField(choices=[('1', 'Manual'), ('2', 'Router'), ('3', 'ReRouter')], default='1', max_length=4),
        ),
    ]
