# Generated by Django 4.0.6 on 2024-04-18 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0054_projectgroup_project_device_type_and_more'),
        ('Surveyentry', '0045_respondentdetail_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondentdetailsrelationalfield',
            name='project_group_sub_supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.projectgroupsubsupplier'),
        ),
    ]
