# Generated by Django 4.0.6 on 2024-04-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0046_respondentdetailsrelationalfield_project_group_sub_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondentprojectdetail',
            name='duplicate_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='respondentprojectdetail',
            name='duplicate_score',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='respondentprojectdetail',
            name='failure_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='respondentprojectdetail',
            name='respondent_risk_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='respondentprojectdetail',
            name='threat_potential_check',
            field=models.BooleanField(default=True),
        ),
    ]
