# Generated by Django 5.0.6 on 2024-07-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0047_respondentprojectdetail_duplicate_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondenturldetail',
            name='userid',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
