# Generated by Django 5.0.6 on 2024-07-15 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0048_respondenturldetail_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespondentDetailTolunaFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirected_survey_incidence', models.IntegerField(null=True)),
                ('redirected_survey_wave_id', models.IntegerField(null=True)),
                ('redirected_survey_quota_id', models.CharField(max_length=100, null=True)),
                ('member_code', models.CharField(max_length=100, null=True, unique=True)),
                ('survey_supply_code', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_code', models.CharField(blank=True, max_length=100, null=True)),
                ('visitor_amount', models.FloatField(null=True)),
                ('country_iso', models.CharField(max_length=5, null=True)),
                ('user_prescreener_response', models.JSONField(max_length=1000, null=True)),
                ('qualified_quota', models.CharField(max_length=1000, null=True)),
                ('respondent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey_entry_toluna_field', to='Surveyentry.respondentdetail')),
            ],
        ),
        migrations.DeleteModel(
            name='RespondentClientSupplyAdditionalParams',
        ),
    ]
