# Generated by Django 4.0.6 on 2024-07-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0049_respondentdetailtolunafields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondentdetail',
            name='us',
            field=models.CharField(choices=[('1', 'Manual'), ('2', 'Router'), ('3', 'ReRouter'), ('4', 'SupplierBuyer'), ('5', 'SubSupplierBuyer')], default='1', max_length=4),
        ),
    ]
