# Generated by Django 4.0.6 on 2024-10-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0050_alter_respondentdetail_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroupprescreenerdatastore',
            name='answer_file',
            field=models.FileField(blank=True, null=True, upload_to='answer_file/'),
        ),
    ]
