# Generated by Django 4.0.6 on 2024-11-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0051_projectgroupprescreenerdatastore_answer_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondentprojectgroupsubsupplier',
            name='hash_value',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='respondentprojectgroupsubsupplier',
            name='sub_supplier_complete_url',
            field=models.URLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='respondentprojectgroupsubsupplier',
            name='sub_supplier_internal_terminate_redirect_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='respondentprojectgroupsubsupplier',
            name='sub_supplier_postback_url',
            field=models.URLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='respondentprojectgroupsubsupplier',
            name='sub_supplier_postback_url_response',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='respondentprojectgroupsubsupplier',
            name='sub_supplier_quotafull_url',
            field=models.URLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='respondentprojectgroupsubsupplier',
            name='sub_supplier_requiredN',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='respondentprojectgroupsubsupplier',
            name='sub_supplier_required_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='respondentprojectgroupsubsupplier',
            name='sub_supplier_securityterminate_url',
            field=models.URLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='respondentprojectgroupsubsupplier',
            name='sub_supplier_terminate_no_project_available',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='respondentprojectgroupsubsupplier',
            name='sub_supplier_terminate_url',
            field=models.URLField(default='', null=True),
        ),
    ]
