# Generated by Django 5.0.6 on 2025-01-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0052_respondentprojectgroupsubsupplier_hash_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondenturldetail',
            name='end_ip_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='respondentprojectdetail',
            name='clientURL',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='respondentprojectgroupsubsupplier',
            name='sub_supplier_complete_url',
            field=models.URLField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='respondentprojectgroupsubsupplier',
            name='sub_supplier_internal_terminate_redirect_url',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='respondentprojectgroupsubsupplier',
            name='sub_supplier_postback_url',
            field=models.URLField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='respondentprojectgroupsubsupplier',
            name='sub_supplier_quotafull_url',
            field=models.URLField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='respondentprojectgroupsubsupplier',
            name='sub_supplier_securityterminate_url',
            field=models.URLField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='respondentprojectgroupsubsupplier',
            name='sub_supplier_terminate_no_project_available',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='respondentprojectgroupsubsupplier',
            name='sub_supplier_terminate_url',
            field=models.URLField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='respondentsupplierdetail',
            name='supplier_complete_url',
            field=models.URLField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='respondentsupplierdetail',
            name='supplier_internal_terminate_redirect_url',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='respondentsupplierdetail',
            name='supplier_postback_url',
            field=models.URLField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='respondentsupplierdetail',
            name='supplier_quotafull_url',
            field=models.URLField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='respondentsupplierdetail',
            name='supplier_securityterminate_url',
            field=models.URLField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='respondentsupplierdetail',
            name='supplier_terminate_no_project_available',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='respondentsupplierdetail',
            name='supplier_terminate_url',
            field=models.URLField(default='', max_length=500, null=True),
        ),
    ]
