# Generated by Django 5.0.6 on 2025-01-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surveyentry', '0053_respondenturldetail_end_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondenturldetail',
            name='user_agent',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
