# Generated by Django 4.0.6 on 2023-08-16 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0010_alter_draftinvoice_id_alter_draftinvoicerow_id_and_more'),
        ('Project', '0041_alter_project_project_revenue_month'),
        ('Sales_Commission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_commission_rows',
            name='amount',
        ),
        migrations.AddField(
            model_name='sales_commission',
            name='commission_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sales_commission_rows',
            name='commission_row_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sales_commission_rows',
            name='invoice_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sales_commission_rows',
            name='invoice_row',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Invoice.invoicerow'),
        ),
        migrations.AlterField(
            model_name='sales_commission',
            name='total_commision_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sales_commission_rows',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.project'),
        ),
    ]
