# Generated by Django 3.1.1 on 2021-05-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_auto_20210516_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroupsupplier',
            name='default_redirect_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='projectgroupsupplier',
            name='postback_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
