# Generated by Django 3.1.1 on 2021-07-15 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0003_auto_20210715_2303'),
        ('Project', '0005_auto_20210527_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectgroupsupplier',
            old_name='postback_url',
            new_name='supplier_postbackurl',
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='panel_reward_points',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_revenue_month',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=7, max_length=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('1', 'Adhoc'), ('2', 'Tracker'), ('3', 'IHUT'), ('4', 'Community Recruit'), ('5', 'Panel Sourcing'), ('6', 'Qual'), ('7', 'IR Check'), ('8', 'Other'), ('9', 'Diary'), ('10', 'Recontact'), ('11', 'Wave Study')], default='5', max_length=2),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='project_group_client_url_type',
            field=models.CharField(choices=[('1', 'Single'), ('2', 'Multiple'), ('3', 'Recontact')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectgroupsupplier',
            name='supplier_completeurl',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='projectgroupsupplier',
            name='supplier_quotafullurl',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='projectgroupsupplier',
            name='supplier_securityterminateurl',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='projectgroupsupplier',
            name='supplier_terminateurl',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.CreateModel(
            name='ScrubProjectSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.projectgroup')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.supplierorganisation')),
            ],
        ),
    ]
