# Generated by Django 3.1.1 on 2021-08-30 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bid', '0001_initial'),
        ('Project', '0008_auto_20210808_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrubprojectsupplier',
            name='source',
        ),
        migrations.AddField(
            model_name='scrubprojectsupplier',
            name='project_group_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.projectgroupsupplier'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Bid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid', to='Bid.bid'),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='project_group_ip_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='project_group_pid_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='project_group_security_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scrubprojectsupplier',
            name='project_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.projectgroup'),
        ),
    ]
