# Generated by Django 3.1.1 on 2021-09-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0011_auto_20210901_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_po_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
