# Generated by Django 3.1.1 on 2021-10-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0012_project_project_po_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectgroupsupplier',
            old_name='default_redirect_url',
            new_name='supplier_internal_terminate_redirect_url',
        ),
        migrations.AddField(
            model_name='projectgroupsupplier',
            name='supplier_terminate_no_project_available',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_revenue_month',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=10, max_length=2),
        ),
    ]
