# Generated by Django 3.1.1 on 2022-01-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0015_auto_20211206_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_criticality_level',
            field=models.CharField(blank=True, choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default='', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_list_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_revenue_month',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_revenue_year',
            field=models.IntegerField(default=2022),
        ),
    ]
