# Generated by Django 3.1.1 on 2022-01-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0016_auto_20220105_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='prj_sticky_board',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='project',
            table='project_project',
        ),
    ]
