# Generated by Django 3.1.1 on 2022-03-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0021_auto_20220329_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Booked', 'Booked'), ('Live', 'Live'), ('Paused', 'Paused'), ('Closed', 'Closed'), ('Reconciled', 'Reconciled'), ('Invoiced', 'Invoiced'), ('Archived', 'Archived')], default='Booked', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='project_group_status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Booked', 'Booked'), ('Live', 'Live'), ('Paused', 'Paused'), ('Closed', 'Closed'), ('Reconciled', 'Reconciled'), ('Invoiced', 'Invoiced'), ('Archived', 'Archived')], default='Booked', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectgroupsupplier',
            name='supplier_status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Booked', 'Booked'), ('Live', 'Live'), ('Paused', 'Paused'), ('Closed', 'Closed'), ('Reconciled', 'Reconciled'), ('Invoiced', 'Invoiced'), ('Archived', 'Archived')], default='Booked', max_length=10),
        ),
    ]
