# Generated by Django 3.1.1 on 2022-04-25 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0023_auto_20220401_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='prjgrp_status_setLive_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='show_on_DIY',
            field=models.BooleanField(default=False),
        ),
    ]
