# Generated by Django 3.1.1 on 2022-04-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0024_auto_20220425_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgroup',
            name='show_on_DIY',
            field=models.BooleanField(default=True),
        ),
    ]
