# Generated by Django 3.1.1 on 2022-06-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0027_auto_20220602_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='research_defender_oe_check',
            field=models.BooleanField(default=True),
        ),
    ]
