# Generated by Django 4.0.6 on 2022-08-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0029_auto_20220802_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Booked', 'Booked'), ('Live', 'Live'), ('Paused', 'Paused'), ('Closed', 'Closed'), ('Reconciled', 'Reconciled'), ('ReadyForInvoice', 'ReadyForInvoice'), ('ReadyForInvoiceApproved', 'ReadyForInvoiceApproved'), ('Invoiced', 'Invoiced'), ('Archived', 'Archived')], default='Live', max_length=30),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='project_group_status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Booked', 'Booked'), ('Live', 'Live'), ('Paused', 'Paused'), ('Closed', 'Closed'), ('Reconciled', 'Reconciled'), ('ReadyForInvoice', 'ReadyForInvoice'), ('ReadyForInvoiceApproved', 'ReadyForInvoiceApproved'), ('Invoiced', 'Invoiced'), ('Archived', 'Archived')], default='Live', max_length=30),
        ),
        migrations.AlterField(
            model_name='projectgroupsupplier',
            name='supplier_status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Booked', 'Booked'), ('Live', 'Live'), ('Paused', 'Paused'), ('Closed', 'Closed'), ('Reconciled', 'Reconciled'), ('ReadyForInvoice', 'ReadyForInvoice'), ('ReadyForInvoiceApproved', 'ReadyForInvoiceApproved'), ('Invoiced', 'Invoiced'), ('Archived', 'Archived')], default='Live', max_length=30),
        ),
    ]
