# Generated by Django 4.0.6 on 2022-12-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0034_alter_project_project_revenue_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_device_type',
            field=models.CharField(choices=[('1', 'All'), ('2', 'Desktop/Laptop Only'), ('3', 'Tablet Only'), ('4', 'Mobile Only'), ('5', 'Dekstop + Tablet'), ('6', 'Dekstop + Mobile'), ('7', 'Tablet + Mobile'), ('8', 'UNKNOWN')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_revenue_month',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=12, max_length=2),
        ),
        migrations.DeleteModel(
            name='ScrubProjectSupplier',
        ),
    ]
