# Generated by Django 4.0.6 on 2023-04-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0035_alter_project_project_device_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Bid',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_revenue_month',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=4, max_length=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_revenue_year',
            field=models.IntegerField(default=2023),
        ),
    ]
