# Generated by Django 4.0.6 on 2023-09-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0042_alter_project_project_revenue_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='custom_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='project_group_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
