# Generated by Django 4.0.6 on 2023-10-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0044_alter_project_project_revenue_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='excluded_project_group',
            field=models.JSONField(blank=True, default=list, max_length=1000),
        ),
    ]
