# Generated by Django 4.0.6 on 2023-12-21 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0021_subsupplierorganisation_subsuppliercontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0047_alter_project_project_revenue_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='ad_enable_panel',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProjectGroupSubSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completes', models.BigIntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('cpi', models.FloatField(default=0)),
                ('sub_supplier_completeurl', models.URLField(blank=True, default='', null=True)),
                ('sub_supplier_terminateurl', models.URLField(blank=True, default='', null=True)),
                ('sub_supplier_quotafullurl', models.URLField(blank=True, default='', null=True)),
                ('sub_supplier_securityterminateurl', models.URLField(blank=True, default='', null=True)),
                ('sub_supplier_postbackurl', models.URLField(blank=True, default='', null=True)),
                ('sub_supplier_survey_url', models.URLField()),
                ('sub_supplier_status', models.CharField(choices=[('Cancel', 'Cancel'), ('Booked', 'Booked'), ('Live', 'Live'), ('Paused', 'Paused'), ('Closed', 'Closed'), ('Reconciled', 'Reconciled'), ('ReadyForInvoice', 'ReadyForInvoice'), ('ReadyForInvoiceApproved', 'ReadyForInvoiceApproved'), ('Invoiced', 'Invoiced'), ('Archived', 'Archived')], default='Live', max_length=30)),
                ('theormReachSupplier_survey_id', models.CharField(max_length=300, null=True, unique=True)),
                ('lucidSupplier_survey_id', models.IntegerField(null=True, unique=True)),
                ('sub_supplier_internal_terminate_redirect_url', models.URLField(blank=True, default='', null=True)),
                ('sub_supplier_terminate_no_project_available', models.URLField(blank=True, default='', null=True)),
                ('created_from_supplier_dashboard', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progrpsubsupp_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progrpsubsupp_modified_by', to=settings.AUTH_USER_MODEL)),
                ('project_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_groups', to='Project.projectgroup')),
                ('project_group_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_group_supplier', to='Project.projectgroupsupplier')),
                ('sub_supplier_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_supplier_orga', to='Supplier.subsupplierorganisation')),
            ],
            options={
                'ordering': ('-modified_at',),
            },
        ),
    ]
