# Generated by Django 4.0.6 on 2024-01-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0048_projectgroup_ad_enable_panel_projectgroupsubsupplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_revenue_month',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_revenue_year',
            field=models.IntegerField(default=2024),
        ),
    ]
