# Generated by Django 4.2.10 on 2024-02-07 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0008_parentquestion_is_routable_and_more'),
        ('Project', '0049_alter_project_project_revenue_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipcode',
            name='question_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Questions.translatedquestion'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_revenue_month',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=2, max_length=2),
        ),
    ]
