# Generated by Django 4.0.6 on 2024-04-14 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0052_alter_project_project_revenue_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjeGroupForceStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('Cancel', 'Cancel'), ('Booked', 'Booked'), ('Live', 'Live'), ('Paused', 'Paused'), ('Closed', 'Closed'), ('Reconciled', 'Reconciled'), ('ReadyForInvoice', 'ReadyForInvoice'), ('ReadyForInvoiceApproved', 'ReadyForInvoiceApproved'), ('Invoiced', 'Invoiced'), ('Archived', 'Archived')], default='Live', max_length=30)),
                ('project_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Project.projectgroup')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGroupStatsCalculations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.IntegerField(default=0)),
                ('starts', models.IntegerField(default=0)),
                ('internal_terminate', models.IntegerField(default=0)),
                ('incompletes', models.IntegerField(default=0)),
                ('completes', models.IntegerField(default=0)),
                ('terminates', models.IntegerField(default=0)),
                ('quota_full', models.IntegerField(default=0)),
                ('security_terminate', models.IntegerField(default=0)),
                ('complete_rejected_by_client', models.IntegerField(default=0)),
                ('client_rejected', models.IntegerField(default=0)),
                ('expense', models.FloatField(default=0)),
                ('revenue', models.FloatField(default=0)),
                ('incidence', models.FloatField(default=0)),
                ('median_LOI', models.FloatField(default=0)),
                ('margin', models.FloatField(default=0)),
                ('project_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Project.projectgroup')),
            ],
        ),
    ]
