# Generated by Django 4.0.6 on 2024-04-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_country_id_alter_employeeprofile_id'),
        ('Project', '0053_projegroupforcestop_projectgroupstatscalculations'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='project_device_type',
            field=models.CharField(choices=[('1', 'All'), ('2', 'Desktop/Laptop Only'), ('3', 'Tablet Only'), ('4', 'Mobile Only'), ('5', 'Dekstop + Tablet'), ('6', 'Dekstop + Mobile'), ('7', 'Tablet + Mobile'), ('8', 'UNKNOWN')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_country',
            field=models.ManyToManyField(blank=True, to='employee.country'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_language',
            field=models.ManyToManyField(blank=True, to='Project.language'),
        ),
    ]
