# Generated by Django 4.0.6 on 2024-04-23 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0054_projectgroup_project_device_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgroupsubsupplier',
            name='project_group_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_group_supplier_fk', to='Project.projectgroupsupplier'),
        ),
    ]
