# Generated by Django 4.0.6 on 2024-04-23 19:45

import Project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0055_alter_projectgroupsubsupplier_project_group_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='duplicate_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='duplicate_score',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='failure_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='failure_reason',
            field=models.JSONField(default=Project.models.failure_reason_default_list, max_length=10000),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='respondent_risk_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='threat_potential_check',
            field=models.BooleanField(default=True),
        ),
    ]
