# Generated by Django 4.0.6 on 2024-05-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0057_alter_project_project_revenue_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='client_survey_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
