# Generated by Django 4.0.6 on 2024-06-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0061_projectcpiapprovedmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('1', 'Adhoc'), ('2', 'Tracker'), ('3', 'IHUT'), ('4', 'Community Recruit'), ('5', 'Panel Sourcing'), ('6', 'Qual'), ('7', 'IR Check'), ('8', 'Other'), ('9', 'Diary'), ('10', 'Recontact'), ('11', 'Wave Study'), ('12', 'Client Supply API Projects'), ('13', 'Dummy Project')], default='5', max_length=2),
        ),
    ]
