# Generated by Django 5.0.6 on 2024-07-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0063_alter_project_project_revenue_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlogtable',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='ProjectGroupLogTable',
        ),
        migrations.DeleteModel(
            name='ProjectLogTable',
        ),
    ]
