# Generated by Django 5.0.6 on 2024-07-18 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0064_remove_projectlogtable_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGroupPriorityStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits', models.IntegerField(default=0)),
                ('completes', models.IntegerField(default=0)),
                ('internal_conversion', models.IntegerField(default=0)),
                ('project_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Project.projectgroup')),
            ],
        ),
    ]
