# Generated by Django 5.0.6 on 2025-01-16 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bid', '0003_bid_bid_category_bid_bid_currency_and_more'),
        ('Project', '0070_alter_project_project_revenue_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ad_scrubproject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bid.bid'),
        ),
        migrations.AlterField(
            model_name='multipleurl',
            name='client_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_revenue_month',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_revenue_year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Booked', 'Booked'), ('Live', 'Live'), ('Paused', 'Paused'), ('Closed', 'Closed'), ('Reconciled', 'Reconciled'), ('ReadyForAudit', 'ReadyForAudit'), ('ReadyForInvoice', 'ReadyForInvoice'), ('ReadyForInvoiceApproved', 'ReadyForInvoiceApproved'), ('Invoiced', 'Invoiced'), ('Archived', 'Archived')], default='Live', max_length=30),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='project_group_liveurl',
            field=models.URLField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='project_group_status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Booked', 'Booked'), ('Live', 'Live'), ('Paused', 'Paused'), ('Closed', 'Closed'), ('Reconciled', 'Reconciled'), ('ReadyForAudit', 'ReadyForAudit'), ('ReadyForInvoice', 'ReadyForInvoice'), ('ReadyForInvoiceApproved', 'ReadyForInvoiceApproved'), ('Invoiced', 'Invoiced'), ('Archived', 'Archived')], default='Live', max_length=30),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='project_group_surveyurl',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='project_group_testurl',
            field=models.URLField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectgroupsubsupplier',
            name='sub_supplier_completeurl',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectgroupsubsupplier',
            name='sub_supplier_internal_terminate_redirect_url',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectgroupsubsupplier',
            name='sub_supplier_postbackurl',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectgroupsubsupplier',
            name='sub_supplier_quotafullurl',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectgroupsubsupplier',
            name='sub_supplier_securityterminateurl',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectgroupsubsupplier',
            name='sub_supplier_status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Booked', 'Booked'), ('Live', 'Live'), ('Paused', 'Paused'), ('Closed', 'Closed'), ('Reconciled', 'Reconciled'), ('ReadyForAudit', 'ReadyForAudit'), ('ReadyForInvoice', 'ReadyForInvoice'), ('ReadyForInvoiceApproved', 'ReadyForInvoiceApproved'), ('Invoiced', 'Invoiced'), ('Archived', 'Archived')], default='Live', max_length=30),
        ),
        migrations.AlterField(
            model_name='projectgroupsubsupplier',
            name='sub_supplier_survey_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='projectgroupsubsupplier',
            name='sub_supplier_terminate_no_project_available',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectgroupsubsupplier',
            name='sub_supplier_terminateurl',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectgroupsupplier',
            name='supplier_completeurl',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectgroupsupplier',
            name='supplier_internal_terminate_redirect_url',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectgroupsupplier',
            name='supplier_postbackurl',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectgroupsupplier',
            name='supplier_quotafullurl',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectgroupsupplier',
            name='supplier_securityterminateurl',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectgroupsupplier',
            name='supplier_status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Booked', 'Booked'), ('Live', 'Live'), ('Paused', 'Paused'), ('Closed', 'Closed'), ('Reconciled', 'Reconciled'), ('ReadyForAudit', 'ReadyForAudit'), ('ReadyForInvoice', 'ReadyForInvoice'), ('ReadyForInvoiceApproved', 'ReadyForInvoiceApproved'), ('Invoiced', 'Invoiced'), ('Archived', 'Archived')], default='Live', max_length=30),
        ),
        migrations.AlterField(
            model_name='projectgroupsupplier',
            name='supplier_survey_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='projectgroupsupplier',
            name='supplier_terminate_no_project_available',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectgroupsupplier',
            name='supplier_terminateurl',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projegroupforcestop',
            name='current_status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Booked', 'Booked'), ('Live', 'Live'), ('Paused', 'Paused'), ('Closed', 'Closed'), ('Reconciled', 'Reconciled'), ('ReadyForAudit', 'ReadyForAudit'), ('ReadyForInvoice', 'ReadyForInvoice'), ('ReadyForInvoiceApproved', 'ReadyForInvoiceApproved'), ('Invoiced', 'Invoiced'), ('Archived', 'Archived')], default='Live', max_length=30),
        ),
        migrations.CreateModel(
            name='ProjectNotesConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.project')),
            ],
        ),
    ]
