# Generated by Django 5.0.6 on 2025-04-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0073_alter_project_project_revenue_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbackup',
            name='Backup_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Backup', 'Backup')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_revenue_month',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=4, max_length=2),
        ),
    ]
