# Generated by Django 3.1.1 on 2021-02-10 17:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=150)),
                ('supplier_address1', models.CharField(max_length=150, null=True)),
                ('supplier_address2', models.CharField(max_length=150, null=True)),
                ('supplier_city', models.CharField(max_length=25, null=True)),
                ('supplier_state', models.CharField(max_length=25, null=True)),
                ('supplier_zip', models.CharField(max_length=10, null=True)),
                ('supplier_completeurl', models.URLField()),
                ('supplier_terminateurl', models.URLField()),
                ('supplier_quotafullurl', models.URLField()),
                ('supplier_securityterminateurl', models.URLField()),
                ('supplier_paymentdetails', models.TextField(null=True)),
                ('supplier_status', models.CharField(choices=[('1', 'Allowed'), ('2', 'Blocked')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supp_org_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supp_org_modified_by', to=settings.AUTH_USER_MODEL)),
                ('supplier_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.country')),
            ],
            options={
                'ordering': ('-modified_at',),
            },
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_firstname', models.CharField(max_length=30)),
                ('supplier_lastname', models.CharField(max_length=30)),
                ('supplier_contactnumber', models.CharField(max_length=14, null=True, validators=[django.core.validators.RegexValidator(message="Contact number must be in the format of '+123456789'. Up to 13 digits allowed.", regex='^\\+?1?\\d{9,13}$')])),
                ('supplier_contact_status', models.BooleanField(default=True)),
                ('supplier_email', models.EmailField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supp_cont_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supp_cont_modified_by', to=settings.AUTH_USER_MODEL)),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.supplierorganisation')),
            ],
            options={
                'ordering': ('-modified_at',),
            },
        ),
    ]
