# Generated by Django 3.1.1 on 2021-05-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorganisation',
            name='default_redirect_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='supplierorganisation',
            name='postback_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='supplierorganisation',
            name='supplier_code',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplierorganisation',
            name='supplier_type',
            field=models.CharField(choices=[('1', 'Manual'), ('2', 'API')], default='1', max_length=1),
        ),
    ]
