# Generated by Django 3.1.1 on 2021-07-15 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0002_auto_20210527_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthKeyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authkey', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('authkey_category', models.CharField(blank=True, choices=[('1', 'DisqoSupplier')], max_length=2, null=True)),
                ('base_url', models.URLField(default='', null=True)),
                ('client_id', models.CharField(max_length=100, null=True)),
                ('supplier_id', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisqoAPIPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_loi', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(1)])),
                ('max_loi', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(1)])),
                ('min_incidence', models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('max_incidence', models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('cpi', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='supplierorganisation',
            name='postback_url',
        ),
        migrations.AddField(
            model_name='supplierorganisation',
            name='supplier_postbackurl',
            field=models.URLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='supplierorganisation',
            name='supplier_rate',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='supplierorganisation',
            name='supplier_rate_model',
            field=models.CharField(choices=[('3', 'Manual'), ('1', 'Flat'), ('2', 'Revenue Sharing')], default='3', max_length=1),
        ),
        migrations.AddField(
            model_name='supplierorganisation',
            name='supplier_routerurl',
            field=models.URLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='supplierorganisation',
            name='supplier_url_code',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplierorganisation',
            name='supplier_completeurl',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='supplierorganisation',
            name='supplier_quotafullurl',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='supplierorganisation',
            name='supplier_securityterminateurl',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='supplierorganisation',
            name='supplier_terminateurl',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='supplierorganisation',
            name='supplier_type',
            field=models.CharField(choices=[('1', 'Manual'), ('2', 'API'), ('3', 'Router'), ('4', 'Panel')], default='1', max_length=1),
        ),
    ]
