# Generated by Django 3.1.1 on 2021-08-31 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0003_auto_20210715_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierAPIAdditionalfield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_security_key', models.CharField(default='', max_length=255, null=True)),
                ('hash_variable_name', models.CharField(default='', max_length=255, null=True)),
                ('enable_hash', models.BooleanField(default=False)),
                ('enable_routing', models.BooleanField(default=False)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Supplier.supplierorganisation')),
            ],
        ),
    ]
