# Generated by Django 3.1.1 on 2021-10-13 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('Supplier', '0004_supplierapiadditionalfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierorganisation',
            old_name='default_redirect_url',
            new_name='supplier_internal_terminate_redirect_url',
        ),
        migrations.AddField(
            model_name='supplierorganisation',
            name='supplier_terminate_no_project_available',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='supplierorganisation',
            name='supplier_postbackurl',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.CreateModel(
            name='SupplierCPIMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpi', models.FloatField(default=0)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.country')),
                ('supplier_org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Supplier.supplierorganisation')),
            ],
        ),
    ]
