# Generated by Django 3.1.1 on 2021-10-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0005_auto_20211013_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercontact',
            name='supplier_email_notify',
            field=models.BooleanField(default=False),
        ),
    ]
