# Generated by Django 3.1.1 on 2021-11-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0006_suppliercontact_supplier_email_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorganisation',
            name='max_authorized_cpi',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='supplierorganisation',
            name='supplier_routerurl',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
