# Generated by Django 3.1.1 on 2021-12-06 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0007_auto_20211129_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierOrgAuthKeyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authkey', models.CharField(blank=True, max_length=200, null=True)),
                ('api_key', models.CharField(blank=True, max_length=200, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=200, null=True)),
                ('staging_base_url', models.URLField(blank=True, null=True)),
                ('production_base_url', models.URLField(blank=True, null=True)),
                ('client_id', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_id', models.CharField(blank=True, max_length=30, null=True)),
                ('supplierOrg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Supplier.supplierorganisation')),
            ],
        ),
        migrations.DeleteModel(
            name='AuthKeyDetail',
        ),
    ]
