# Generated by Django 3.1.1 on 2022-02-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0008_auto_20211206_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercontact',
            name='send_final_ids',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='suppliercontact',
            name='send_supplier_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='suppliercontact',
            name='supplier_dashboard_registration',
            field=models.BooleanField(default=False),
        ),
    ]
