# Generated by Django 3.1.1 on 2022-03-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0009_auto_20220211_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorganisation',
            name='supplier_TAX_id',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
    ]
