# Generated by Django 3.1.1 on 2022-04-16 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0010_supplierorganisation_supplier_tax_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorganisation',
            name='supplier_rate',
            field=models.CharField(default=0.5, max_length=5),
        ),
        migrations.CreateModel(
            name='SupplierBuyerAPIModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_api_enable', models.BooleanField(default=False)),
                ('secret_key', models.CharField(max_length=255, unique=True)),
                ('supplier_org_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_buyer_apid', to='Supplier.supplierorganisation')),
            ],
        ),
    ]
