# Generated by Django 4.0.6 on 2022-08-03 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_country_theorem_country_id'),
        ('Supplier', '0012_auto_20220602_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorganisation',
            name='max_completes_on_diy',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='SupplierInvoicingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_address1', models.TextField()),
                ('inv_address2', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=25)),
                ('mobile_no', models.CharField(max_length=20)),
                ('supp_tax_no', models.CharField(max_length=50)),
                ('supp_contact_emailID', models.EmailField(max_length=80)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.country')),
                ('finalIDs_email_addresses', models.ManyToManyField(to='Supplier.suppliercontact')),
                ('mangemnt_primary_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_invoice_details', to='Supplier.suppliercontact')),
                ('supplier_org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_invoice_details', to='Supplier.supplierorganisation')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierBankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_address', models.TextField()),
                ('bank_account_no', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=50, null=True)),
                ('swift_code', models.CharField(max_length=50, null=True)),
                ('iban_routing_code', models.CharField(max_length=50, null=True)),
                ('supplier_inv_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_bank_detail', to='Supplier.supplierinvoicingdetails')),
            ],
        ),
    ]
