# Generated by Django 4.0.6 on 2022-11-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0014_alter_disqoapipricing_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierbuyerapimodel',
            name='question_type',
            field=models.CharField(choices=[('1', 'Parent Question ID'), ('2', 'Translated Question ID'), ('3', 'Question Mapping')], default='2', max_length=2),
        ),
        migrations.AddField(
            model_name='supplierbuyerapimodel',
            name='request_api_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='supplierorganisation',
            name='supplier_type',
            field=models.CharField(choices=[('1', 'Manual'), ('2', 'API'), ('3', 'Router'), ('4', 'Panel'), ('5', 'Offerwall')], default='1', max_length=1),
        ),
    ]
