# Generated by Django 4.0.6 on 2022-11-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0015_supplierbuyerapimodel_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorganisation',
            name='supplier_type',
            field=models.CharField(choices=[('1', 'Manual'), ('2', 'API'), ('3', 'Router'), ('4', 'Panel')], default='1', max_length=1),
        ),
    ]
