# Generated by Django 4.0.6 on 2022-12-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0016_alter_supplierorganisation_supplier_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorganisation',
            name='total_surveyside_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplierorganisation',
            name='visitor_survey_side',
            field=models.CharField(choices=[('1', 'Client-Side'), ('2', 'Supplier-Side'), ('3', 'Both')], default='3', max_length=1),
        ),
    ]
