# Generated by Django 4.0.6 on 2023-04-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0017_supplierorganisation_total_surveyside_counts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierorganisation',
            name='total_surveyside_counts',
        ),
        migrations.RemoveField(
            model_name='supplierorganisation',
            name='visitor_survey_side',
        ),
    ]
