# Generated by Django 4.0.6 on 2023-05-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0018_remove_supplierorganisation_total_surveyside_counts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercontact',
            name='supplier_mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
