# Generated by Django 4.0.6 on 2023-12-06 16:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_country_id_alter_employeeprofile_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Supplier', '0020_alter_supplierorganisation_supplier_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSupplierOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_supplier_code', models.CharField(default='', max_length=50, null=True)),
                ('sub_supplier_name', models.CharField(max_length=150)),
                ('max_completes_on_diy', models.IntegerField(default=10)),
                ('sub_supplier_address1', models.CharField(max_length=150, null=True)),
                ('sub_supplier_address2', models.CharField(max_length=150, null=True)),
                ('sub_supplier_city', models.CharField(max_length=25, null=True)),
                ('sub_supplier_state', models.CharField(max_length=25, null=True)),
                ('sub_supplier_zip', models.CharField(max_length=10, null=True)),
                ('sub_supplier_TAX_id', models.CharField(blank=True, default='N/A', max_length=50, null=True)),
                ('sub_supplier_completeurl', models.URLField(default='', null=True)),
                ('sub_supplier_terminateurl', models.URLField(default='', null=True)),
                ('sub_supplier_quotafullurl', models.URLField(default='', null=True)),
                ('sub_supplier_securityterminateurl', models.URLField(default='', null=True)),
                ('sub_supplier_postbackurl', models.URLField(blank=True, default='', null=True)),
                ('sub_supplier_routerurl', models.URLField(blank=True, default='', null=True)),
                ('sub_supplier_rate_model', models.CharField(choices=[('3', 'Manual'), ('1', 'Flat'), ('2', 'Revenue Sharing')], default='3', max_length=1)),
                ('sub_supplier_rate', models.CharField(default=0.5, max_length=5)),
                ('sub_supplier_paymentdetails', models.TextField(null=True)),
                ('sub_supplier_status', models.CharField(choices=[('1', 'Allowed'), ('2', 'Blocked')], default='1', max_length=1)),
                ('sub_supplier_internal_terminate_redirect_url', models.URLField(blank=True, default='', null=True)),
                ('sub_supplier_terminate_no_project_available', models.URLField(blank=True, default='', null=True)),
                ('sub_supplier_url_code', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('max_authorized_cpi', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsupp_org_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsupp_org_modified_by', to=settings.AUTH_USER_MODEL)),
                ('sub_supplier_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.country')),
                ('supplier_org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_supplier_buyer_apid', to='Supplier.supplierorganisation')),
            ],
            options={
                'ordering': ('-modified_at',),
            },
        ),
        migrations.CreateModel(
            name='SubSupplierContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsupplier_firstname', models.CharField(max_length=30)),
                ('subsupplier_lastname', models.CharField(max_length=30)),
                ('subsupplier_contactnumber', models.CharField(max_length=14, null=True, validators=[django.core.validators.RegexValidator(message="Contact number must be in the format of '+123456789'. Up to 13 digits allowed.", regex='^\\+?1?\\d{9,13}$')])),
                ('subsupplier_contact_status', models.BooleanField(default=True)),
                ('subsend_supplier_updates', models.BooleanField(default=True)),
                ('subsupplier_dashboard_registration', models.BooleanField(default=False)),
                ('subsend_final_ids', models.BooleanField(default=True)),
                ('subsupplier_email_notify', models.BooleanField(default=False)),
                ('subsupplier_email', models.EmailField(max_length=80)),
                ('subsupplier_mail_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsupp_cont_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsupp_cont_modified_by', to=settings.AUTH_USER_MODEL)),
                ('subsupplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.subsupplierorganisation')),
            ],
            options={
                'ordering': ('-modified_at',),
            },
        ),
    ]
