# Generated by Django 4.0.6 on 2024-02-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0021_subsupplierorganisation_subsuppliercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsupplierorganisation',
            name='sub_supplier_quality_type',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='supplierorganisation',
            name='supplier_quality_type',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default='1', max_length=1),
        ),
    ]
