# Generated by Django 4.0.6 on 2024-06-11 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyBankDetails', '0003_alter_companyinvoicebankdetail_company_iban_number_and_more'),
        ('Customer', '0006_customerorganization_threat_potential_score'),
        ('Supplier', '0022_subsupplierorganisation_sub_supplier_quality_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorganisation',
            name='company_bank_detail',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='CompanyBankDetails.companydetails'),
        ),
        migrations.AddField(
            model_name='supplierorganisation',
            name='cpi_calculation_method',
            field=models.CharField(choices=[('1', 'Including GST'), ('2', 'Excluding GST')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='supplierorganisation',
            name='supplier_currency',
            field=models.ForeignKey(default=156, on_delete=django.db.models.deletion.CASCADE, to='Customer.currency'),
        ),
    ]
