# Generated by Django 4.0.6 on 2024-07-24 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0023_supplierorganisation_company_bank_detail_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplierBuyerAPIModel',
        ),
    ]
