# Generated by Django 4.0.6 on 2022-08-09 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0003_alter_customerorganization_options_and_more'),
        ('CompanyBankDetails', '0001_initial'),
        ('Invoice', '0009_alter_invoicerow_row_po_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_receipt_amount', models.FloatField()),
                ('bank_charges', models.FloatField()),
                ('payment_receipt_date', models.DateField()),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_description', models.TextField(null=True)),
                ('bank_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CompanyBankDetails.companyinvoicebankdetail')),
                ('customer_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customerorganization')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPaymentReceiptInvoiceLinking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_received_amount', models.FloatField()),
                ('tds_amount', models.FloatField()),
                ('client_payment_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientSupplierInvoicePayment.clientpaymentreceipt')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Invoice.invoice')),
            ],
        ),
    ]
