# Generated by Django 4.0.6 on 2022-12-20 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_currency_client_currency_id_and_more'),
        ('ClientSupplierInvoicePayment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpaymentreceipt',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.currency'),
        ),
    ]
