# Generated by Django 4.0.6 on 2022-08-03 21:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0003_country_theorem_country_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInvoiceBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ifsc_code', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('bank_address', models.TextField(blank=True, default='', null=True)),
                ('swift_code', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('account_type', models.CharField(blank=True, choices=[('1', 'Current'), ('2', 'Saving'), ('3', 'Checking Account')], default='1', max_length=10, null=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('company_contact_number', models.CharField(max_length=14, null=True, validators=[django.core.validators.RegexValidator(message="Contact number must be in the format of '+123456789'. Up to 13 digits allowed.", regex='^\\+?1?\\d{9,13}$')])),
                ('company_address1', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('company_address2', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('company_city', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('company_state', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('company_zipcode', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('company_email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('company_website', models.URLField(blank=True, default='', max_length=300, null=True)),
                ('company_tax_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('company_cin_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_pan_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('company_iban_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('company_routing_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('company_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_invoice_data_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_invoice_data_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
