# Generated by Django 4.0.6 on 2023-11-24 15:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_country_id_alter_employeeprofile_id'),
        ('Customer', '0006_customerorganization_threat_potential_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CompanyBankDetails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinvoicebankdetail',
            name='company_address1',
        ),
        migrations.RemoveField(
            model_name='companyinvoicebankdetail',
            name='company_address2',
        ),
        migrations.RemoveField(
            model_name='companyinvoicebankdetail',
            name='company_cin_number',
        ),
        migrations.RemoveField(
            model_name='companyinvoicebankdetail',
            name='company_city',
        ),
        migrations.RemoveField(
            model_name='companyinvoicebankdetail',
            name='company_contact_number',
        ),
        migrations.RemoveField(
            model_name='companyinvoicebankdetail',
            name='company_country',
        ),
        migrations.RemoveField(
            model_name='companyinvoicebankdetail',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='companyinvoicebankdetail',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='companyinvoicebankdetail',
            name='company_pan_number',
        ),
        migrations.RemoveField(
            model_name='companyinvoicebankdetail',
            name='company_state',
        ),
        migrations.RemoveField(
            model_name='companyinvoicebankdetail',
            name='company_tax_number',
        ),
        migrations.RemoveField(
            model_name='companyinvoicebankdetail',
            name='company_website',
        ),
        migrations.RemoveField(
            model_name='companyinvoicebankdetail',
            name='company_zipcode',
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('company_contact_number', models.CharField(max_length=14, null=True, validators=[django.core.validators.RegexValidator(message="Contact number must be in the format of '+123456789'. Up to 13 digits allowed.", regex='^\\+?1?\\d{9,13}$')])),
                ('company_address1', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('company_address2', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('company_city', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('company_state', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('company_zipcode', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('company_email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('company_website', models.URLField(blank=True, default='', max_length=300, null=True)),
                ('company_tax_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('company_cin_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_pan_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('company_invoice_prefix_local_currency', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('company_invoice_prefix_international_currency', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('company_invoice_suffix_local_currency', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('company_invoice_suffix_international_currency', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('company_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.country')),
                ('company_local_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Customer.currency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_details_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_details_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='companyinvoicebankdetail',
            name='company_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CompanyBankDetails.companydetails'),
        ),
    ]
