# Generated by Django 4.0.6 on 2023-11-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyBankDetails', '0002_remove_companyinvoicebankdetail_company_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinvoicebankdetail',
            name='company_iban_number',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='companyinvoicebankdetail',
            name='company_routing_number',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
