# Generated by Django 5.0.6 on 2024-07-04 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project', '0063_alter_project_project_revenue_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierBuyerProjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.JSONField(default=dict)),
                ('project_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Project.projectgroup')),
            ],
        ),
    ]
