# Generated by Django 4.0.6 on 2024-07-24 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0024_delete_supplierbuyerapimodel'),
        ('SupplierBuyerAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierBuyerAPIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_api_enable', models.BooleanField(default=False)),
                ('secret_key', models.CharField(max_length=255, unique=True)),
                ('request_api_url', models.URLField(blank=True, default='')),
                ('supplier_org_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_buyer_apid', to='Supplier.supplierorganisation')),
            ],
        ),
        migrations.CreateModel(
            name='SubSupplierBuyerAPIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_api_enable', models.BooleanField(default=False)),
                ('secret_key', models.CharField(max_length=255, unique=True)),
                ('request_api_url', models.URLField(blank=True, default='')),
                ('sub_supplier_org_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sub_supplier_buyer_apid', to='Supplier.subsupplierorganisation')),
            ],
        ),
    ]
