# Generated by Django 5.0.6 on 2025-01-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupplierBuyerAPI', '0002_supplierbuyerapimodel_subsupplierbuyerapimodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsupplierbuyerapimodel',
            name='request_api_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='supplierbuyerapimodel',
            name='request_api_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
