# Generated by Django 5.0.6 on 2024-12-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientSupplierAPIErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputdata', models.TextField()),
                ('client_name', models.CharField(blank=True, max_length=50, null=True)),
                ('line_number', models.CharField(blank=True, max_length=50, null=True)),
                ('error_details', models.CharField(blank=True, max_length=5000, null=True)),
                ('project_group_number', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientSupplierEnableDisableAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(choices=[('toluna', 'toluna'), ('zamplia', 'zamplia'), ('sago', 'sago')], max_length=50)),
                ('is_enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientSupplierFetchSurveysLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(choices=[('toluna', 'toluna'), ('zamplia', 'zamplia'), ('sago', 'sago')], max_length=50)),
                ('total_surveys_fetch', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpinionsDealErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputdata', models.TextField()),
                ('client_name', models.CharField(blank=True, max_length=50, null=True)),
                ('line_number', models.CharField(blank=True, max_length=50, null=True)),
                ('error_details', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
