# Generated by Django 3.1.1 on 2021-02-10 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default='', max_length=50)),
                ('invoice_description', models.TextField(blank=True, null=True)),
                ('invoice_po_number', models.TextField(default='')),
                ('invoice_status', models.CharField(choices=[('1', 'Draft'), ('2', 'Sent'), ('3', 'Paid')], default='1', max_length=1)),
                ('invoice_total_amount', models.FloatField(default=0)),
                ('invoice_subtotal_amount', models.FloatField(default=0)),
                ('invoice_date', models.DateField()),
                ('invoice_due_date', models.DateField()),
                ('invoice_ship_to_address_enable', models.BooleanField(default=True)),
                ('invoice_tax', models.CharField(choices=[('1', 'None'), ('2', 'IGST'), ('3', 'SGST/CGST')], default='1', max_length=1)),
                ('invoice_IGST_value', models.FloatField(default=0)),
                ('invoice_SGST_value', models.FloatField(default=0)),
                ('invoice_CGST_value', models.FloatField(default=0)),
                ('invoice_TDS_amount', models.FloatField(default=0)),
                ('invoice_TDS_percentage', models.FloatField(default=0)),
                ('invoice_show_stamp', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_created_by', to=settings.AUTH_USER_MODEL)),
                ('invoice_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.clientcontact')),
                ('invoice_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customerorganization')),
                ('invoice_project', models.ManyToManyField(to='Project.Project')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_name', models.CharField(max_length=255)),
                ('row_completes', models.IntegerField(default=0)),
                ('row_cpi', models.FloatField(default=0)),
                ('row_total_amount', models.FloatField(default=0)),
                ('row_description', models.TextField(default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_row_created_by', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Invoice.invoice')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_row_modified_by', to=settings.AUTH_USER_MODEL)),
                ('project_group_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.projectgroup')),
            ],
        ),
    ]
