# Generated by Django 3.1.1 on 2021-09-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0002_invoice_invoice_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_conversion_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_show_conversion_rate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_total_amount_in_USD',
            field=models.FloatField(default=0),
        ),
    ]
