# Generated by Django 3.1.1 on 2021-10-26 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0003_auto_20210930_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='invoicerow',
            options={'ordering': ('id',)},
        ),
    ]
