# Generated by Django 3.1.1 on 2021-12-13 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0005_auto_20211129_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-id',)},
        ),
    ]
