# Generated by Django 4.0.6 on 2022-08-03 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0030_alter_project_project_status_and_more'),
        ('CompanyBankDetails', '__first__'),
        ('Customer', '0003_alter_customerorganization_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Invoice', '0007_auto_20220113_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm_email_file', models.FileField(blank=True, max_length=500, null=True, upload_to='invoice_confirmation_attachment/')),
                ('invoice_total', models.FloatField(blank=True, null=True)),
                ('conversion_rate', models.FloatField(blank=True, null=True)),
                ('cpi_calculation_method', models.CharField(blank=True, choices=[('1', 'Including GST'), ('2', 'Excluding GST')], max_length=1, null=True)),
                ('draft_approved', models.BooleanField(default=False)),
                ('approval_note', models.TextField(blank=True, null=True)),
                ('notes_from_pm', models.TextField(blank=True, null=True)),
                ('project_invoiced_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_invoice_created_by', to=settings.AUTH_USER_MODEL)),
                ('invoice_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.currency')),
                ('invoice_to_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.customerorganization')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_invoice_modified_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.project')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_invoice_bank_detail',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='CompanyBankDetails.companyinvoicebankdetail'),
        ),
        migrations.AddField(
            model_name='invoicerow',
            name='row_hsn_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoicerow',
            name='row_po_number',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='invoicerow',
            name='row_project_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.project'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_po_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InvoicePaymentReminderEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_payment_reminder_email', to=settings.AUTH_USER_MODEL)),
                ('invoices', models.ManyToManyField(to='Invoice.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='DraftInvoiceRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('bid_cpi', models.FloatField(default=0)),
                ('cpi', models.FloatField(default=0)),
                ('completes', models.IntegerField(default=0)),
                ('total', models.FloatField(default=0)),
                ('draft_invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Invoice.draftinvoice')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
