# Generated by Django 4.0.6 on 2022-08-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0008_draftinvoice_invoice_company_invoice_bank_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicerow',
            name='row_po_number',
            field=models.TextField(blank=True, default=''),
        ),
    ]
