# Generated by Django 4.0.6 on 2023-09-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0010_alter_draftinvoice_id_alter_draftinvoicerow_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='prefix',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='suffix',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
