# Generated by Django 4.0.6 on 2024-03-14 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_customerorganization_threat_potential_score'),
        ('Invoice', '0011_invoice_prefix_invoice_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepaymentreminderemail',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Customer.customerorganization'),
        ),
    ]
