# Generated by Django 4.0.6 on 2024-05-28 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Invoice', '0012_invoicepaymentreminderemail_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceExceptionsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_data', models.CharField(blank=True, max_length=10000, null=True)),
                ('exception_raise', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Invoice.invoice')),
            ],
        ),
    ]
