# Generated by Django 4.0.6 on 2024-06-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0013_invoiceexceptionslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftinvoice',
            name='confirm_email_file',
            field=models.FileField(blank=True, max_length=5000, null=True, upload_to='invoice_confirmation_attachment/'),
        ),
    ]
