# Generated by Django 5.0.6 on 2024-07-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0014_alter_draftinvoice_confirm_email_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceExceptionsLog',
        ),
    ]
