# Generated by Django 5.0.6 on 2025-01-16 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_customerorganization_threat_potential_score'),
        ('Invoice', '0015_delete_invoiceexceptionslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='draftinvoice',
            name='Accountant_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='draftinvoice',
            name='BA_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='draftinvoice',
            name='BA_approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_invoice_ba_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='draftinvoice',
            name='bid_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_invoice_bid_currency', to='Customer.currency'),
        ),
        migrations.AddField(
            model_name='draftinvoicerow',
            name='bid_total',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='DraftInvoiceChangesStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_date', models.DateTimeField(null=True)),
                ('payload_data', models.JSONField(max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_invoice_create_update_approved_approved_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_invoice_create_update_approved_created_by', to=settings.AUTH_USER_MODEL)),
                ('draft_invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Invoice.draftinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='DraftInvoiceNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_invoice_notes_created_by', to=settings.AUTH_USER_MODEL)),
                ('draft_invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Invoice.draftinvoice')),
            ],
        ),
    ]
