# Generated by Django 5.0.6 on 2025-01-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0016_draftinvoice_accountant_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftinvoice',
            name='bid_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
