# Generated by Django 3.1.1 on 2021-07-15 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project', '0006_auto_20210715_2308'),
        ('employee', '0001_initial'),
        ('Customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_number', models.CharField(max_length=20)),
                ('bid_name', models.CharField(max_length=255)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('bid_type', models.CharField(choices=[('1', 'Adhoc'), ('2', 'Tracker'), ('3', 'IHUT'), ('4', 'Community Recruit'), ('5', 'Panel Sourcing'), ('6', 'Qual'), ('7', 'IR Check'), ('8', 'Other')], max_length=2)),
                ('bid_description', models.TextField()),
                ('bid_status', models.CharField(choices=[('1', 'Draft'), ('2', 'Sent'), ('3', 'Won'), ('4', 'Cancel')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('client_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.clientcontact')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_created_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customerorganization')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_modified_by', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_project_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BidRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_row_type', models.CharField(choices=[('1', 'Gen-Pop'), ('2', 'B2B Easy'), ('3', 'B2B Hard'), ('4', 'Healthcare/Ailment')], max_length=1)),
                ('bid_row_incidence', models.IntegerField(default=0)),
                ('bid_row_loi', models.IntegerField(default=0)),
                ('bid_row_required_N', models.IntegerField(default=0)),
                ('bid_row_feasible_N', models.IntegerField(default=0)),
                ('bid_row_cpi', models.FloatField(default=0)),
                ('bid_row_total', models.FloatField(default=0)),
                ('bid_row_description', models.TextField(default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidrow', to='Bid.bid')),
                ('bid_row_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.country')),
                ('bid_row_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.language')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_row_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_row_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
