# Generated by Django 5.0.6 on 2025-01-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bid', '0003_bid_bid_category_bid_bid_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_type',
            field=models.CharField(choices=[('1', 'Adhoc'), ('2', 'Tracker'), ('3', 'IHUT'), ('4', 'Community Recruit'), ('5', 'Panel Sourcing'), ('6', 'Qual'), ('7', 'IR Check'), ('8', 'Other'), ('9', 'Diary'), ('10', 'Recontact'), ('11', 'Wave Study'), ('12', 'Client Supply API Projects'), ('13', 'Dummy Project')], max_length=2),
        ),
    ]
