# Generated by Django 5.0.6 on 2025-02-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bid', '0004_alter_bid_bid_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidrow',
            name='bid_row_type',
            field=models.CharField(choices=[('1', 'Gen-Pop'), ('2', 'B2B Easy'), ('3', 'B2B Hard'), ('4', 'Healthcare/Ailment'), ('5', 'consumer'), ('6', 'other')], max_length=1),
        ),
    ]
