# Generated by Django 5.0.6 on 2025-02-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bid', '0005_alter_bidrow_bid_row_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_won_date',
            field=models.DateField(null=True),
        ),
    ]
