# Generated by Django 3.1.1 on 2021-07-15 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Supplier', '0003_auto_20210715_2303'),
        ('Questions', '0002_auto_20210715_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_api_que_key', models.CharField(max_length=85, null=True)),
                ('parent_que_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Questions.parentquestion')),
                ('supplier_org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Supplier.supplierorganisation')),
            ],
        ),
        migrations.CreateModel(
            name='AnswersMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_api_ans_key', models.CharField(max_length=85, null=True)),
                ('parent_ans_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Questions.parentanswer')),
                ('supplier_org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Supplier.supplierorganisation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='questionsmapping',
            constraint=models.UniqueConstraint(fields=('supplier_org', 'parent_que_id'), name='unique_supplier_parent_que'),
        ),
        migrations.AddConstraint(
            model_name='answersmapping',
            constraint=models.UniqueConstraint(fields=('supplier_org', 'parent_ans_id'), name='unique_supplier_parent_ans'),
        ),
    ]
