# Generated by Django 3.1.1 on 2021-11-29 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionSupplierAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='answersmapping',
            name='unique_supplier_parent_ans',
        ),
        migrations.AddField(
            model_name='answersmapping',
            name='ques_mapping_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='QuestionSupplierAPI.questionsmapping'),
        ),
        migrations.AddConstraint(
            model_name='answersmapping',
            constraint=models.UniqueConstraint(fields=('supplier_org', 'parent_ans_id', 'ques_mapping_id'), name='unique_supplier_parent_ans'),
        ),
    ]
