# Generated by Django 4.0.6 on 2022-08-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionSupplierAPI', '0002_auto_20211129_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersmapping',
            name='supplier_api_ans_parameter',
            field=models.CharField(max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='questionsmapping',
            name='supplier_api_que_parameter',
            field=models.CharField(max_length=85, null=True),
        ),
        migrations.AlterField(
            model_name='answersmapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='questionsmapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
